/* ============================================================
   2027 S/S VOCA — data.js
   심슨보카 Day 01~10, 500단어 (엑셀 Day_01-10.xlsx 에서 추출)
   각 항목: { id, day, no, word, meaning, memo }
   ============================================================ */

var VOCAB_DATA = [
  { id: 1001, day: 1, no: 1, word: 'contain', meaning: 'v. 포함하다, 함유하다; 억제하다', memo: 'con(함께) + tain(잡다) → 속엘 함께 붙잡아 두다 💡 무엇을 담다/포함하다.' },
  { id: 1002, day: 1, no: 2, word: 'obtain', meaning: 'v. 얻다, 획득하다', memo: 'ob(강조) + tain(잡다) → 손에 꽉 붙잡아 쥐다 💡 권리나 물건을 얻다/획득하다.' },
  { id: 1003, day: 1, no: 3, word: 'maintain', meaning: 'v. 유지하다, 지속하다; 주장하다', memo: 'main(손=manu) + tain(잡다) → 손으로 꼭 붙잡고 계속 유지하다 💡 상태를 유지하다.' },
  { id: 1004, day: 1, no: 4, word: 'sustain', meaning: 'v. 떠받치다, 지탱하다; 유지하다, 지속하다', memo: 'sus(아래에서) + tain(잡다) → 아래에서 무게를 붙잡아 받치다 💡 건물을 지탱하다/유지하다.' },
  { id: 1005, day: 1, no: 5, word: 'retain', meaning: 'v. 유지하다, 보유하다', memo: 're(뒤에/계속) + tain(잡다) → 내 뒤에 꼭 붙들어 두고 놓지 않다 💡 지위나 정보를 보유하다.' },
  { id: 1006, day: 1, no: 6, word: 'habitual', meaning: 'a. 습관적인', memo: 'habit(버릇, 습관) + ual(형용사미) → 몸에 배어 있는 버릇의 💡 습관적인 행동.' },
  { id: 1007, day: 1, no: 7, word: 'habitat', meaning: 'n. 서식지, 거주지', memo: 'habit(살다, 거주하다) + at → 생물이 모여 사는 장소 💡 동물들의 자연 서식지.' },
  { id: 1008, day: 1, no: 8, word: 'inhabit', meaning: 'v. 살다, 거주하다', memo: 'in(안에) + habit(살다) → 집이나 지역 안에서 살아가다 💡 곳에 거주하다.' },
  { id: 1009, day: 1, no: 9, word: 'exhibit', meaning: 'v. 전시[진열]하다; 나타내다, 보이다', memo: 'ex(밖으로) + hibit(가지다/잡다) → 물건을 밖으로 꺼내어 보이게 하다 💡 작품을 전시하다.' },
  { id: 1010, day: 1, no: 10, word: 'prohibit', meaning: 'v. 금지하다, 막다, 방해하다', memo: 'pro(앞에서) + hibit(잡다) → 앞으로 다가가지 못하게 붙잡아 막다 💡 행동을 금지하다.' },
  { id: 1011, day: 1, no: 11, word: 'inhibit', meaning: 'v. 억제하다', memo: 'in(안에) + hibit(잡다) → 마음속 깊은 곳에서 꽉 붙잡아 누르다 💡 감정이나 충동을 억제하다.' },
  { id: 1012, day: 1, no: 12, word: 'consume', meaning: 'v. 소비[소모]하다; 먹다, 마시다', memo: 'con(완전히) + sume(쓰다/사다) → 완전히 다 써버리다 💡 에너지를 소비하다.' },
  { id: 1013, day: 1, no: 13, word: 'resume', meaning: 'v. 다시 시작하다, 재개하다 n. 이력서[résumé]', memo: 're(다시) + sume(취하다/시작하다) → 멈췄던 일을 다시 집어 들다 💡 업무를 재개하다.' },
  { id: 1014, day: 1, no: 14, word: 'assume', meaning: 'v. 가정하다, 추정하다; (역할·임무 등을) (맡)다, (책임을) 지다; (태도를) 취하다; (양상을) 띠다; -인 체하다, 가장하다', memo: 'as( ~쪽으로) + sume(취하다) → 책임을 자기 쪽으로 취해 맡다 💡 책임을 지다/가정하다.' },
  { id: 1015, day: 1, no: 15, word: 'presume', meaning: 'v. 추정하다, 간주하다', memo: 'pre(미리) + sume(취하다) → 증거가 없어도 미리 앞서서 짐작하다 💡 사실로 추정하다.' },
  { id: 1016, day: 1, no: 16, word: 'perceive', meaning: 'v. 인지하다, 알아차리다', memo: 'per(완전히) + ceive(잡다/취하다) → 속까지 확실하게 파악하여 느끼다 💡 변화를 인지하다.' },
  { id: 1017, day: 1, no: 17, word: 'deceive', meaning: 'v. 속이다, 기만하다', memo: 'de(아래로/나쁘게) + ceive(잡다) → 상대의 눈을 흐려 낚아채듯 속이다 💡 남을 기만하다.' },
  { id: 1018, day: 1, no: 18, word: 'conceive', meaning: 'v. (생각을) 품다, 상상하다; 임신하다', memo: 'con(함께) + ceive(잡다) → 머릿속에 아이디어나 생명을 함께 품다 💡 생각을 품다/임신하다.' },
  { id: 1019, day: 1, no: 19, word: 'intercept', meaning: 'v. 가로채다; 가로막다', memo: 'inter(사이에) + cept(잡다) → 오가는 도중 중간에서 낚아채다 💡 패스나 물건을 가로채다.' },
  { id: 1020, day: 1, no: 20, word: 'susceptible', meaning: 'a. (병에) 걸리기 쉬운, 취약한, 영향받기 쉬운, 민감한', memo: 'sus(아래에서) + cept(잡다) + ible → 외부의 공격을 아래에서 쉽게 받아내는 💡 병에 취약한.' },
  { id: 1021, day: 1, no: 21, word: 'serve', meaning: 'v. 봉사[복무]하다, 제공하다; 역할을 하다, 도움이 되다', memo: 'serve(섬기다/제공하다) → 남을 위해 일하거나 물건을 내놓다 💡 식사를 제공하다/역할을 하다.' },
  { id: 1022, day: 1, no: 22, word: 'preserve', meaning: 'v. 보존[보호]하다, 지키다', memo: 'pre(미리/앞서서) + serve(지키다) → 상하지 않도록 미리 잘 관리하여 지키다 💡 자연을 보존하다.' },
  { id: 1023, day: 1, no: 23, word: 'conserve', meaning: 'v. 보존[보호]하다, 아끼다', memo: 'con(함께/완전히) + serve(지키다) → 자원을 낭비하지 않고 알뜰히 모아 지키다 💡 에너지를 절약하다.' },
  { id: 1024, day: 1, no: 24, word: 'reserve', meaning: 'v. 예약하다; 비축하다, 남겨 두다 n. 예비, 비축', memo: 're(뒤로) + serve(두다) → 나중을 위해 뒤쪽에 따로 떼어 두다 💡 좌석을 예약하다/비축하다.' },
  { id: 1025, day: 1, no: 25, word: 'observe', meaning: 'v. 관찰하다; (법 등을) 준수하다, 지키다; 말하다, 언급하다', memo: 'ob(앞에) + serve(지켜보다) → 대상을 바깥에서 주의 깊게 지켜보다 💡 규칙을 준수하다/관찰하다.' },
  { id: 1026, day: 1, no: 26, word: 'factual', meaning: 'a. 사실적인, 사실에 입각한', memo: 'fact(사실/만들어진 것) + ual → 실제 사실에 바탕을 둔 💡 사실적인 내용.' },
  { id: 1027, day: 1, no: 27, word: 'facility', meaning: 'n. 시설, 설비; 편의, 손쉬움', memo: 'fac(만들다/쉽게) + ility → 무엇을 쉽게 이용할 수 있게 만든 편의 시설 💡 공공 시설/편의.' },
  { id: 1028, day: 1, no: 28, word: 'facilitate', meaning: 'v. 쉽게[용이하게] 하다, 촉진시키다', memo: 'facil(쉬운) + itate(동사미) → 일을 한결 수월하고 편하게 만들다 💡 학습을 촉진하다/용이하게 하다.' },
  { id: 1029, day: 1, no: 29, word: 'proficient', meaning: 'a. 능숙한, 숙련된', memo: 'pro(앞으로) + fic(만들다/나아가다) + ient → 실력이 앞서 나갈 정도로 능숙해진 💡 전문가처럼 능숙한.' },
  { id: 1030, day: 1, no: 30, word: 'sufficient', meaning: 'a. 충분한', memo: 'suf(아래에서 채우다) + fic(만들다) + ient → 밑에서부터 가득 차올라 모자람이 없는 💡 양이 충분한.' },
  { id: 1031, day: 1, no: 31, word: 'deficient', meaning: 'a. 부족한, 결함이 있는', memo: 'de(아래로/모자란) + fic(만들다) + ient → 채워야 할 양에 미치지 못하고 모자란 💡 영양분이 부족한.' },
  { id: 1032, day: 1, no: 32, word: 'formula', meaning: 'n. 식, (수학) 공식', memo: 'form(형태/모양) + ula(작은 명사미) → 규칙적인 형태나 틀로 만든 식 💡 수학 공식.' },
  { id: 1033, day: 1, no: 33, word: 'uniform', meaning: 'n. 제복, 유니폼 a. 획일적인, 균일한, 한결같은', memo: 'uni(하나의) + form(모양) → 모두 똑같은 하나의 모양으로 맞춘 💡 획일적인 제복.' },
  { id: 1034, day: 1, no: 34, word: 'inform', meaning: 'v. 알리다, 통지하다', memo: 'in(안에) + form(모양/정보를 심다) → 상대의 머릿속에 정보를 심어 알려주다 💡 소식을 알리다.' },
  { id: 1035, day: 1, no: 35, word: 'reform', meaning: 'v. 개혁하다, 개선하다 n. 개혁, 개선', memo: 're(다시) + form(모양) → 낡은 형태를 새롭고 바르게 다시 고치다 💡 제도를 개혁하다.' },
  { id: 1036, day: 1, no: 36, word: 'conform', meaning: 'v. 따르다, 순응하다, 맞추다 (to)', memo: 'con(함께) + form(모양) → 남들과 모양과 기준을 똑같이 맞추어 따르다 💡 규정에 순응하다.' },
  { id: 1037, day: 1, no: 37, word: 'transform', meaning: 'v. 변형시키다, 바꾸다', memo: 'trans(이동/변화) + form(모양) → 모양이나 성질을 완전히 다른 형태로 바꾸다 💡 에너지를 변환하다.' },
  { id: 1038, day: 1, no: 38, word: 'pose', meaning: 'v. (문제 등을) 제기[제시]하다, 야기하다; 자세를 취하다', memo: 'pose(두다/위치시키다) → 문제나 질문을 앞에 툭 던져 두다 💡 문제를 제기하다/자세를 취하다.' },
  { id: 1039, day: 1, no: 39, word: 'compose', meaning: 'v. 구성하다; 작곡하다, 작문하다', memo: 'com(함께) + pose(두다) → 여러 요소들을 한데 모아 작품이나 조직을 만들다 💡 글을 작문하다.' },
  { id: 1040, day: 1, no: 40, word: 'propose', meaning: 'v. 제안[제의]하다', memo: 'pro(앞에) + pose(두다) → 의견이나 안건을 상대 앞에 내놓다 💡 아이디어를 제안하다.' },
  { id: 1041, day: 1, no: 41, word: 'expose', meaning: 'v. 노출시키다, 드러내다; 폭로하다', memo: 'ex(밖으로) + pose(두다) → 감춰져 있던 것을 바깥으로 꺼내어 드러내다 💡 비밀을 폭로하다.' },
  { id: 1042, day: 1, no: 42, word: 'suppose', meaning: 'v. 생각하다, 가정하다', memo: 'sup(아래에서) + pose(두다) → 마음속 밑바닥에 생각을 깔아두고 추정하다 💡 사실이라 가정하다.' },
  { id: 1043, day: 1, no: 43, word: 'oppose', meaning: 'v. 반대하다, 대항하다', memo: 'op(반대로) + pose(두다) → 상대의 의견 앞에 맞서서 버티다 💡 정책에 반대하다.' },
  { id: 1044, day: 1, no: 44, word: 'impose', meaning: 'v. 부과하다; 강요하다', memo: 'im(안으로/위에) + pose(두다) → 무거운 부담이나 세금을 얹어 놓다 💡 세금을 부과하다.' },
  { id: 1045, day: 1, no: 45, word: 'dispose', meaning: 'v. 배치하다; 처리[처분]하다 (of)', memo: 'dis(이리저리) + pose(두다) → 물건을 제자리에 이리저리 잘 배치하거나 치우다 💡 쓰레기를 처분하다.' },
  { id: 1046, day: 1, no: 46, word: 'include', meaning: 'v. 포함하다', memo: 'in(안에) + clude(잠그다/닫다) → 울타리 안쪽에 가두어 함께 포함시키다 💡 비용을 포함하다.' },
  { id: 1047, day: 1, no: 47, word: 'exclude', meaning: 'v. 제외하다, 빼제하다', memo: 'ex(밖으로) + clude(닫다) → 문을 밖으로 닫아버리고 아예 안 들여보내다 💡 명단에서 제외하다.' },
  { id: 1048, day: 1, no: 48, word: 'conclude', meaning: 'v. 결론짓다, 끝내다; 결정[결심]하다', memo: 'con(완전히) + clude(닫다) → 논의의 문을 완전히 닫고 결말을 맺다 💡 회의를 결론짓다.' },
  { id: 1049, day: 1, no: 49, word: 'disclose', meaning: 'v. 드러내다, 폭로하다', memo: 'dis(반대로/열다) + close(닫다) → 꼭 닫혀 있던 문을 열어젖혀 비밀을 밝히다 💡 진실을 폭로하다.' },
  { id: 1050, day: 1, no: 50, word: 'enclose', meaning: 'v. 동봉하다, 에워싸다', memo: 'en(안에) + close(닫다) → 편지 봉투나 울타리 안쪽으로 꼭 닫아 넣다 💡 서류를 동봉하다.' },
  { id: 2001, day: 2, no: 1, word: 'exceed', meaning: 'v. 넘다, 초과하다; 능가하다, 우월하다', memo: 'ex(밖으로) + ceed(가다) → 한도를 넘어서 가다 💡 범위를 넘어서다/초과하다.' },
  { id: 2002, day: 2, no: 2, word: 'proceed', meaning: 'v. 나아가다, (계속) 진행하다', memo: 'pro(앞으로) + ceed(가다) → 앞을 향해 계속 나아가다 💡 일을 진행하다/나아가다.' },
  { id: 2003, day: 2, no: 3, word: 'precede', meaning: 'v. ~에 선행하다[앞서다], ~보다 먼저 일어나다; ~보다 우선하다', memo: 'pre(먼저) + cede(가다) → 남보다 먼저 가다 💡 선행하다/앞서다.' },
  { id: 2004, day: 2, no: 4, word: 'recede', meaning: 'v. 후퇴하다, 물러나다; 약해지다', memo: 're(뒤로) + cede(가다) → 뒤로 물러나 가다 💡 뒤로 물러나다/약해지다.' },
  { id: 2005, day: 2, no: 5, word: 'access', meaning: 'n. 접근, 이용, 출입 v. 접근하다, 이용하다', memo: 'ac( ~쪽으로) + cess(가다) → 목적지를 향해 다가가다 💡 장소나 정보에 접근하다/이용하다.' },
  { id: 2006, day: 2, no: 6, word: 'predecessor', meaning: 'n. 전임자, 선배', memo: 'predecessor (precede의 명사형 파생) → 먼저 앞서 있던 사람 💡 전임자/선배.' },
  { id: 2007, day: 2, no: 7, word: 'grade', meaning: 'n. 등급, 단계, 학년, 성적 v. 등급을 매기다', memo: 'grade(단계, 등급 어원 자체) → 단계나 등급을 나누다 💡 등급을 매기다/성적.' },
  { id: 2008, day: 2, no: 8, word: 'gradual', meaning: 'a. 단계적인, 점진적인', memo: 'grad(단계, 걸음) + ual(형용사미) → 한 걸음씩 단계적으로 나아가는 💡 점진적인/단계적인.' },
  { id: 2009, day: 2, no: 9, word: 'ingredient', meaning: 'n. (요리) 재료, 성분, 구성 요소', memo: 'in(안에) + gred(가다) + ient(~하는 것) → 속에 들어가 구성하는 것 💡 재료/성분.' },
  { id: 2010, day: 2, no: 10, word: 'regress', meaning: 'v. 퇴보하다, 퇴행하다', memo: 're(뒤로) + gress(가다) → 뒤쪽으로 걸음을 옮기다 💡 다시 퇴보하다/퇴행하다.' },
  { id: 2011, day: 2, no: 11, word: 'sequence', meaning: 'n. 연속적인 사건들; 순서, 차례', memo: 'sequ(따르다) + ence(명사미) → 차례대로 줄지어 따르는 것 💡 순서/차례/연속.' },
  { id: 2012, day: 2, no: 12, word: 'consequence', meaning: 'n. 결과, 영향; 중요성', memo: 'con(함께) + sequ(따르다) + ence → 일이 일어난 뒤에 함께 따르는 것 💡 그에 따른 결과/영향.' },
  { id: 2013, day: 2, no: 13, word: 'subsequent', meaning: 'a. 그 다음의, 차후의', memo: 'sub(아래에/뒤에) + sequ(따르다) + ent → 뒤이어 따라오는 💡 그 다음의/차후의.' },
  { id: 2014, day: 2, no: 14, word: 'consecutive', meaning: 'a. 연속적인, 계속되는', memo: 'con(함께) + secut(따르다) + ive → 잇달아 함께 계속되는 💡 연속적인/계속되는.' },
  { id: 2015, day: 2, no: 15, word: 'persecute', meaning: 'v. 박해하다', memo: 'per(완전히/해롭게) + secut(따르다) → 끝까지 쫓아가 괴롭히다 💡 끈질기게 박해하다.' },
  { id: 2016, day: 2, no: 16, word: 'suit', meaning: 'v. 적합하다, 어울리다 n. 정장, 한 벌의 옷; (법률) 소송', memo: 'suit(따르다/맞추다) → 몸이나 상황에 딱 들어맞다 💡 꼭 맞다/정장.' },
  { id: 2017, day: 2, no: 17, word: 'pursue', meaning: 'v. 추구하다; 뒤쫓다, 추적하다', memo: 'pur(앞으로/intensive) + sue(따르다) → 목표를 향해 바짝 뒤쫓다 💡 꿈을 추구하다/추적하다.' },
  { id: 2018, day: 2, no: 18, word: 'avenue', meaning: 'n. 대로, 가(街)', memo: 'a( ~쪽으로) + ven(오다) + ue → 사람이 모여 오가는 큰 길 💡 대로/가나다.' },
  { id: 2019, day: 2, no: 19, word: 'revenue', meaning: 'n. 세입, 수입', memo: 're(다시) + ven(오다) + ue → 돈이 다시 들어오는 것 💡 나라나 기업의 세입/수입.' },
  { id: 2020, day: 2, no: 20, word: 'adventure', meaning: 'n. 모험(심) v. 모험하다, 위험을 무릅쓰다', memo: 'ad( ~쪽으로) + vent(오다) + ure → 앞으로 다가올 미지의 일을 겪다 💡 모험하다.' },
  { id: 2021, day: 2, no: 21, word: 'advent', meaning: 'n. 출현, 도래', memo: 'ad( ~쪽으로) + vent(오다) → 새로운 시대나 사건이 다가와 출현하다 💡 출현/도래.' },
  { id: 2022, day: 2, no: 22, word: 'conventional', meaning: 'a. 관습[관례]적인, 전통적인', memo: 'convention(관습, 대회) + al → 예로부터 전해 내려오는 방식의 💡 관습적인/전통적인.' },
  { id: 2023, day: 2, no: 23, word: 'prefer', meaning: 'v. 선호하다, 더 좋아하다', memo: 'pre(먼저) + fer(나르다/품다) → 남보다 먼저 마음이 가는 쪽으로 향하다 💡 선호하다.' },
  { id: 2024, day: 2, no: 24, word: 'confer', meaning: 'v. 상의하다, 회의하다; 수여하다', memo: 'con(함께) + fer(나르다) → 의견이나 상을 함께 모아 나누다 💡 상의하다/수여하다.' },
  { id: 2025, day: 2, no: 25, word: 'infer', meaning: 'v. 추론[추측]하다', memo: 'in(안으로) + fer(나르다) → 마음속으로 단서를 모아 결론을 끌어내다 💡 추론하다.' },
  { id: 2026, day: 2, no: 26, word: 'defer', meaning: 'v. 미루다, 연기하다; 존중하다', memo: 'de(아래로/멀리) + fer(나르다) → 일을 뒤로 미루어 치워두다 💡 연기하다/미루다.' },
  { id: 2027, day: 2, no: 27, word: 'fertile', meaning: 'a. 비옥한, 생산력 있는[많이 낳는]; 풍부한', memo: 'fert(나르다/생산하다) + ile → 열매와 산물을 잘 만들어내는 💡 비옥한/풍부한.' },
  { id: 2028, day: 2, no: 28, word: 'sentiment', meaning: 'n. 감정, 정서; 감상', memo: 'sent(느끼다) + iment(명사미) → 마음으로 느끼는 감정 💡 감정/정서.' },
  { id: 2029, day: 2, no: 29, word: 'resent', meaning: 'v. 분개하다, 불쾌하게 여기다', memo: 're(뒤로/반대로) + sent(느끼다) → 마음이 상해 반발심을 느끼다 💡 분개하다/불쾌해하다.' },
  { id: 2030, day: 2, no: 30, word: 'consent', meaning: 'v. 동의[허락]하다 (to) n. 동의[허락], 합의', memo: 'con(함께) + sent(느끼다) → 마음이 서로 똑같이 통하다 💡 동의하다/허락하다.' },
  { id: 2031, day: 2, no: 31, word: 'assent', meaning: 'v. 동의(찬성)하다 (to) n. 동의, 찬성, 승인', memo: 'as( ~에) + sent(느끼다) → 상대방의 생각과 마음이 일치하다 💡 찬성하다/동의하다.' },
  { id: 2032, day: 2, no: 32, word: 'pathetic', meaning: 'a. 불쌍한, 애처로운', memo: 'path(감정/고통) + etic → 슬픈 감정을 자아내는 💡 마음 아픈/불쌍한.' },
  { id: 2033, day: 2, no: 33, word: 'sympathy', meaning: 'n. 동정, 연민; 공감', memo: 'sym(함께) + path(고통/느끼다) → 남의 고통을 함께 느끼다 💡 동정/공감.' },
  { id: 2034, day: 2, no: 34, word: 'empathy', meaning: 'n. 감정 이입, 공감', memo: 'em(안에) + path(감정) → 남의 마음 안으로 들어가 함께 느끼다 💡 감정 이입.' },
  { id: 2035, day: 2, no: 35, word: 'antipathy', meaning: 'n. 반감, 혐오', memo: 'anti(반대로) + path(감정) → 마음이 반대로 작용하여 싫어하다 💡 반감/혐오.' },
  { id: 2036, day: 2, no: 36, word: 'intact', meaning: 'a. 온전한, 손상되지 않은', memo: 'in(not) + tact(만지다) → 아무도 손대지 않아 그대로 보존된 💡 손상 없는/온전한.' },
  { id: 2037, day: 2, no: 37, word: 'tactile', meaning: 'a. 촉각의', memo: 'tact(만지다) + ile → 손으로 만져서 느낄 수 있는 💡 촉각의.' },
  { id: 2038, day: 2, no: 38, word: 'tangible', meaning: 'a. 만질 수 있는, 유형(有形)의; 실질적인, 확실한', memo: 'tang(만지다) + ible → 손으로 만질 수 있는 실체가 있는 💡 만질 수 있는/유형의.' },
  { id: 2039, day: 2, no: 39, word: 'integrate', meaning: 'v. 통합시키다', memo: 'integr(온전한) + ate(동사미) → 흩어진 것들을 하나로 온전하게 합치다 💡 통합시키다.' },
  { id: 2040, day: 2, no: 40, word: 'contagious', meaning: 'a. 전염되는, 전염성의', memo: 'con(함께) + tag(만지다) + ious → 접촉을 통해 함께 옮겨지는 💡 전염성의.' },
  { id: 2041, day: 2, no: 41, word: 'contaminate', meaning: 'v. 더럽히다, 오염시키다', memo: 'con(완전히) + tamin(더럽히다) + ate → 완전히 더러운 상태로 만들다 💡 오염시키다.' },
  { id: 2042, day: 2, no: 42, word: 'spirit', meaning: 'n. 영혼, 정신; 기운, 활기', memo: 'spir(숨쉬다) + it → 몸 안에서 숨 쉬게 하는 생명력 💡 정신/활기.' },
  { id: 2043, day: 2, no: 43, word: 'respire', meaning: 'v. 호흡하다, 숨 쉬다', memo: 're(다시) + spire(숨쉬다) → 숨을 내쉬고 다시 들이쉬다 💡 호흡하다.' },
  { id: 2044, day: 2, no: 44, word: 'inspire', meaning: 'v. (감정·생각을) 불어넣다, 영감을 주다; 고무[격려]하다', memo: 'in(안으로) + spire(숨쉬다) → 마음속에 생기 있는 바람을 불어넣다 💡 영감을 주다.' },
  { id: 2045, day: 2, no: 45, word: 'aspire', meaning: 'v. 열망하다, 갈망하다 (to)', memo: 'a( ~쪽으로) + spire(숨쉬다) → 간절한 마음으로 숨을 몰아쉬며 바라다 💡 열망하다.' },
  { id: 2046, day: 2, no: 46, word: 'expire', meaning: 'v. 만료되다', memo: 'ex(밖으로) + pire(숨쉬다) → 숨이 몸 밖으로 다 빠져나가 끝나다 💡 기간이 만료되다.' },
  { id: 2047, day: 2, no: 47, word: 'conspire', meaning: 'v. 공모하다, 음모를 꾸미다', memo: 'con(함께) + spire(숨쉬다) → 은밀하게 숨을 같이 쉬며 작당하다 💡 몰래 공모하다.' },
  { id: 2048, day: 2, no: 48, word: 'illusion', meaning: 'n. 환상, 환각; 착각, 오해', memo: 'il(안에) + lus(속이다/빛) → 눈에 보이는 허깨비나 착각 💡 환상/착각.' },
  { id: 2049, day: 2, no: 49, word: 'delude', meaning: 'v. 속이다', memo: 'de(아래로/잘못) + lud(놀다/속이다) → 상대방을 가지고 놀며 속이다 💡 현혹하여 속이다.' },
  { id: 2050, day: 2, no: 50, word: 'allude', meaning: 'v. 넌지시 언급하다, 암시하다', memo: 'al( ~쪽에) + lud(놀다/살짝 건드리다) → 핵심을 직접 말하지 않고 살짝 비쳐 말하다 💡 암시하다.' },
  { id: 3001, day: 3, no: 1, word: 'respect', meaning: 'v. 존경하다 n. 존경; (측)면', memo: 're(다시) + spect(보다) → 상대의 눈을 다시 공경히 바라보다 💡 존경하다/측면.' },
  { id: 3002, day: 3, no: 2, word: 'inspect', meaning: 'v. 조사하다', memo: 'in(안에) + spect(보다) → 안쪽까지 꼼꼼히 들여다보다 💡 상태를 조사하다.' },
  { id: 3003, day: 3, no: 3, word: 'suspect', meaning: 'v. 의심하다 n. 혐의자, 용의자', memo: 'sus(아래에서) + spect(보다) → 밑에서 의심스러운 눈으로 훔쳐보다 💡 범인으로 의심하다.' },
  { id: 3004, day: 3, no: 4, word: 'retrospect', meaning: 'v. 회고하다, 회상하다 n. 회상, 추억', memo: 'retro(뒤로) + spect(보다) → 지나온 과거를 뒤돌아보다 💡 옛일을 회고하다.' },
  { id: 3005, day: 3, no: 5, word: 'perspective', meaning: 'n. 관점, 시각', memo: 'per(통하여) + spect(보다) + ive → 사물을 통틀어 바라보는 시선 💡 세상을 보는 관점.' },
  { id: 3006, day: 3, no: 6, word: 'introspective', meaning: 'a. 자기 성찰의, 자기반성의; 내성적인', memo: 'intro(안으로) + spect(보다) + ive → 마음 안쪽을 들여다보는 💡 자기반성의 성향.' },
  { id: 3007, day: 3, no: 7, word: 'spectator', meaning: 'n. 관객, 구경꾼', memo: 'spect(보다) + ator(사람) → 경기나 공연을 구경하는 사람 💡 경기장의 관객.' },
  { id: 3008, day: 3, no: 8, word: 'spectacular', meaning: 'a. 장관을 이루는, 극적인', memo: 'spect(보다) + acular(형용사미) → 눈을 뗄 수 없이 볼 만한 💡 장관을 이루는 풍경.' },
  { id: 3009, day: 3, no: 9, word: 'specify', meaning: 'v. 명시하다, 구체화하다', memo: 'spec(보다/모양) + ify(만들다) → 어떤 사항을 정확히 콕 집어 나타내다 💡 조건을 명시하다.' },
  { id: 3010, day: 3, no: 10, word: 'specific', meaning: 'a. 구체적인, 분명한; 특정한', memo: 'spec(구체적 형태) + ific(만드는) → 확실하게 눈에 보이도록 정해진 💡 구체적인 설명.' },
  { id: 3011, day: 3, no: 11, word: 'speculate', meaning: 'v. 사색하다, 추측하다', memo: 'spec(보다) + ulate(동사미) → 머릿속으로 여러 가능성을 이리저리 그려보다 💡 깊이 사색하다.' },
  { id: 3012, day: 3, no: 12, word: 'despise', meaning: 'v. 경멸하다, 혐오하다', memo: 'de(아래로) + spise(보다=spect) → 아래로 깔아뭉개듯 낮추어보다 💡 사람을 경멸하다.' },
  { id: 3013, day: 3, no: 13, word: 'conspicuous', meaning: 'a. 눈에 띄는, 뚜렷한', memo: 'con(완전히) + spic(보다) + uous → 한눈에 띌 정도로 환하게 잘 보이는 💡 눈에 띄는 특징.' },
  { id: 3014, day: 3, no: 14, word: 'visible', meaning: 'a. 눈에 보이는; 명백한', memo: 'vis(보다) + ible(~할 수 있는) → 육안으로 쉽게 볼 수 있는 💡 눈에 보이는 변화.' },
  { id: 3015, day: 3, no: 15, word: 'supervise', meaning: 'v. 감독하다, 관리하다', memo: 'super(위에) + vise(보다) → 위에서 전체적으로 내려다보며 감시하다 💡 현장을 감독하다.' },
  { id: 3016, day: 3, no: 16, word: 'revise', meaning: 'v. 수정하다, 개정하다', memo: 're(다시) + vise(보다) → 글이나 계획을 다시 살펴보고 고치다 💡 법안을 수정하다.' },
  { id: 3017, day: 3, no: 17, word: 'devise', meaning: 'v. 고안하다, 궁리하다', memo: 'de(완전히) + vise(마음속으로 구상하다) → 머리를 짜내어 새로운 것을 만들어내다 💡 방법을 고안하다.' },
  { id: 3018, day: 3, no: 18, word: 'envision', meaning: 'v. 상상하다, 마음속에 그리다', memo: 'en(안에) + vis(보다) + ion → 마음속 스크린에 미래를 그려 넣다 💡 미래를 상상하다.' },
  { id: 3019, day: 3, no: 19, word: 'improvise', meaning: 'v. 즉흥적으로 하다', memo: 'im(아님/부정) + provise(미리 준비하다) → 미리 대비하지 않고 즉석에서 하다 💡 즉흥적으로 연주하다.' },
  { id: 3020, day: 3, no: 20, word: 'describe', meaning: 'v. 묘사하다, 서술하다', memo: 'de(완전히) + scribe(쓰다) → 대상의 특징을 낱낱이 글로 써서 표현하다 💡 사건을 묘사하다.' },
  { id: 3021, day: 3, no: 21, word: 'inscribe', meaning: 'v. 쓰다, 새기다', memo: 'in(안에) + scribe(쓰다) → 돌이나 나무 표면 깊숙이 글자를 새겨넣다 💡 이름을 새기다.' },
  { id: 3022, day: 3, no: 22, word: 'prescribe', meaning: 'v. 처방하다; 규정하다', memo: 'pre(미리) + scribe(쓰다) → 약이나 규칙을 미리 적어주다 💡 약을 처방하다.' },
  { id: 3023, day: 3, no: 23, word: 'manuscript', meaning: 'n. 원고, 손으로 쓴 책', memo: 'manu(손) + script(쓰다) → 손으로 직접 작성한 문서 💡 책의 초고 원고.' },
  { id: 3024, day: 3, no: 24, word: 'paragraph', meaning: 'n. 문단, 단락, 절', memo: 'para(옆에) + graph(쓰다) → 본문 옆에 단락별로 구분해 적은 글 💡 글의 한 문단.' },
  { id: 3025, day: 3, no: 25, word: 'biography', meaning: 'n. 전기, 일대기', memo: 'bio(생명/삶) + graphy(기록) → 한 사람의 생애를 기록한 책 💡 위인 전기.' },
  { id: 3026, day: 3, no: 26, word: 'geography', meaning: 'n. 지리학', memo: 'geo(땅) + graphy(기록) → 지구의 땅 모양과 환경을 연구하는 학문 💡 지리학.' },
  { id: 3027, day: 3, no: 27, word: 'vocal', meaning: 'a. 목소리의 n. vocal, 노래 부분', memo: 'voc(소리치다/목소리) + al → 목소리와 관련된 💡 보컬 음성.' },
  { id: 3028, day: 3, no: 28, word: 'vocation', meaning: 'n. 천직, 소명; 직업', memo: 'voc(부르다) + ation → 하늘이 자신을 불러준 천직 💡 평생의 직업.' },
  { id: 3029, day: 3, no: 29, word: 'advocate', meaning: 'v. 지지하다, 옹호하다; 주장하다 n. 지지자, 옹호자; 변호사', memo: 'ad(~쪽으로) + voc(목소리) + ate → 편에 서서 목소리를 높여 돕다 💡 정책을 지지하다.' },
  { id: 3030, day: 3, no: 30, word: 'provoke', meaning: 'v. (특정 반응을) 유발하다; 화나게 하다', memo: 'pro(앞으로) + voke(소리치다) → 감정을 자극해 밖으로 터져 나오게 하다 💡 갈등을 유발하다.' },
  { id: 3031, day: 3, no: 31, word: 'evoke', meaning: 'v. 불러내다 (기억·감정을) 일깨우다', memo: 'e(밖으로) + voke(부르다) → 잠들어 있던 추억이나 감정을 끄집어내다 💡 옛 기억을 떠올리다.' },
  { id: 3032, day: 3, no: 32, word: 'revoke', meaning: 'v. 취소하다, 폐지하다', memo: 're(뒤로) + voke(부르다) → 했던 말이나 법을 다시 불러들여 무효로 하다 💡 면허를 취소하다.' },
  { id: 3033, day: 3, no: 33, word: 'dictate', meaning: 'v. 명령[지시]하다; 받아쓰게 하다; 영향을 주다, 좌우하다 n. 명령, 지시 [주로 pl.]', memo: 'dict(말하다) + ate → 입으로 불러주어 그대로 쓰게 하거나 지시하다 💡 규칙을 지시하다.' },
  { id: 3034, day: 3, no: 34, word: 'contradict', meaning: 'v. 모순되다; 반박하다, 반대하다', memo: 'contra(반대로) + dict(말하다) → 상대의 말에 정반대로 맞서 말하다 💡 주장과 모순되다.' },
  { id: 3035, day: 3, no: 35, word: 'indicate', meaning: 'v. 나타내다, 암시하다; 가리키다, 표시하다', memo: 'in(안에) + dic(말하다/가리키다) + ate → 손가락으로 콕 찍어 가리키다 💡 방향을 가리키다.' },
  { id: 3036, day: 3, no: 36, word: 'dedicate', meaning: 'v. 바치다, 헌신하다, 전념하다', memo: 'de(완전히) + dic(바치다/말하다) + ate → 일생을 온전히 통째로 바치다 💡 연구에 헌신하다.' },
  { id: 3037, day: 3, no: 37, word: 'claim', meaning: 'v. 요구하다, 주장하다 n. 요구, 주장', memo: 'claim(소리치다/부르짖다) → 권리를 달라고 큰소리로 당당히 요구하다 💡 권리를 주장하다.' },
  { id: 3038, day: 3, no: 38, word: 'exclaim', meaning: 'v. 소리치다, 외치다', memo: 'ex(밖으로) + claim(소리치다) → 놀라서 감탄을 밖으로 크게 내뱉다 💡 감탄하며 소리치다.' },
  { id: 3039, day: 3, no: 39, word: 'proclaim', meaning: 'v. 선언[선포]하다', memo: 'pro(앞에) + claim(외치다) → 대중 앞에서 공식적으로 크게 알리다 💡 독립을 선포하다.' },
  { id: 3040, day: 3, no: 40, word: 'acclaim', meaning: 'v. 칭송하다, 환호하다', memo: 'ac(~쪽으로) + claim(소리치다) → 박수치며 환호의 소리를 보내다 💡 선수를 칭송하다.' },
  { id: 3041, day: 3, no: 41, word: 'reclaim', meaning: 'v. 되찾다; 개간하다', memo: 're(다시) + claim(찾으러 외치다) → 빼앗겼거나 묻혀 있던 것을 다시 찾아오다 💡 권리를 되찾다.' },
  { id: 3042, day: 3, no: 42, word: 'portable', meaning: 'a. 휴대용의, 가지고 다닐 수 있는', memo: 'port(나르다) + able(~할 수 있는) → 손에 들고 쉽게 옮길 수 있는 💡 휴대용 기기.' },
  { id: 3043, day: 3, no: 43, word: 'transport', meaning: 'v. 운송하다, 수송하다 n. 운송(업), 수송', memo: 'trans(이동) + port(나르다) → 이리저리 물품을 실어 나르다 💡 화물을 수송하다.' },
  { id: 3044, day: 3, no: 44, word: 'import', meaning: 'v. 수입하다 n. 수입', memo: 'im(안으로) + port(나르다) → 외국 물건을 국내 안으로 사들이는 것 💡 원자재 수입.' },
  { id: 3045, day: 3, no: 45, word: 'deport', meaning: 'v. (국외로) 추방하다', memo: 'de(밖으로/멀리) + port(나르다) → 나라 밖으로 강제로 실어 보내다 💡 불법 체류자를 추방하다.' },
  { id: 3046, day: 3, no: 46, word: 'impress', meaning: 'v. 깊은 인상을 주다, 감동시키다', memo: 'im(안에) + press(누르다) → 마음에 도장을 꾹 누르듯 강한 인상을 남기다 💡 깊은 인상을 주다.' },
  { id: 3047, day: 3, no: 47, word: 'depress', meaning: 'v. 낙담시키다, 우울하게 하다', memo: 'de(아래로) + press(누르다) → 기분을 바닥으로 꾹 내리누르다 💡 마음을 우울하게 하다.' },
  { id: 3048, day: 3, no: 48, word: 'suppress', meaning: 'v. (감정을) 참다, 억누르다; 진압하다', memo: 'sup(아래로) + press(누르다) → 치솟는 감정이나 반란을 꾹 눌러 잠재우다 💡 감정을 억누르다.' },
  { id: 3049, day: 3, no: 49, word: 'oppress', meaning: 'v. 탄압하다, 억압하다', memo: 'op(강하게/대항하여) + press(누르다) → 백성이나 약자를 짓누르고 괴롭히다 💡 자유를 억압하다.' },
  { id: 3050, day: 3, no: 50, word: 'repress', meaning: 'v. (감정을) 참다, 억누르다', memo: 're(뒤로) + press(누르다) → 올라오려는 충동을 뒤로 꾹 밀어 넣다 💡 분노를 참다.' },
  { id: 4001, day: 4, no: 1, word: 'produce', meaning: 'v. 생산하다, 제조하다; (결과 등을) 낳다 n. 농산물', memo: 'pro(앞으로) + duce(이끌다) → 앞으로 결과나 물건을 이끌어내다 💡 물건을 생산하다.' },
  { id: 4002, day: 4, no: 2, word: 'reduce', meaning: 'v. 줄이다, 축소하다', memo: 're(아래로) + duce(이끌다) → 수치나 양을 아래로 이끌어 낮추다 💡 규모를 줄이다.' },
  { id: 4003, day: 4, no: 3, word: 'induce', meaning: 'v. 유도하다, 설득하다; 유발하다, 일으키다', memo: 'in(안으로) + duce(이끌다) → 마음속으로 생각을 이끌어내어 설득하다 💡 행동을 유도하다.' },
  { id: 4004, day: 4, no: 4, word: 'deduce', meaning: 'v. 연역하다, 추론하다', memo: 'de(아래로/결과로) + duce(이끌다) → 단서로부터 결론을 이끌어내다 💡 사실을 추론하다.' },
  { id: 4005, day: 4, no: 5, word: 'conduct', meaning: 'v. 수행하다; 경영하다; 인도하다, 지휘하다 n. 행위, 실시', memo: 'con(완전히) + duct(이끌다) → 전체를 이끌며 일을 수행하다 💡 업무를 수행하다.' },
  { id: 4006, day: 4, no: 6, word: 'attract', meaning: 'v. 마음을 끌다, 매혹하다', memo: 'at(~쪽으로) + tract(끌다) → 시선이나 마음을 내 쪽으로 끌어당기다 💡 사람의 마음을 끌다.' },
  { id: 4007, day: 4, no: 7, word: 'subtract', meaning: 'v. 빼다, 공제하다', memo: 'sub(아래에서) + tract(끌다) → 전체에서 아래로 살짝 끌어내어 빼다 💡 숫자를 빼다.' },
  { id: 4008, day: 4, no: 8, word: 'distract', meaning: 'v. (주의를) 딴 데로 돌리다, 산만하게 하다', memo: 'dis(다른 곳으로) + tract(끌다) → 주의를 사방으로 끌어가 흐트러뜨리다 💡 주의를 딴 데로 돌리다.' },
  { id: 4009, day: 4, no: 9, word: 'contract', meaning: 'v. 계약하다; 수축하다[시키다]; (병에) 걸리다 n. 계약, 계약서', memo: 'con(함께) + tract(끌다) → 서로 조건을 끌어당겨 묶다 💡 계약을 맺다/수축하다.' },
  { id: 4010, day: 4, no: 10, word: 'extract', meaning: 'v. 뽑아내다, 추출하다; 발췌하다 n. 추출물; 발췌', memo: 'ex(밖으로) + tract(끌다) → 속에서 성분을 밖으로 쭈욱 끌어내다 💡 액체를 추출하다.' },
  { id: 4011, day: 4, no: 11, word: 'abstract', meaning: 'a. 추상적인; 난해한, 심오한 n. 요약, 발췌 v. 추출하다; 요약하다; 발췌하다', memo: 'abs(멀리) + tract(끌다) → 구체적인 것에서 멀리 끌어내어 개념화하다 💡 추상적인 개념.' },
  { id: 4012, day: 4, no: 12, word: 'trace', meaning: 'v. 추적하다, 찾아내다; (역사적으로) 거슬러 올라가다 n. 자국, 흔적; 극미량, 조금', memo: 'trace(발자국/자국) → 남겨진 자국을 따라가다 💡 흔적을 추적하다.' },
  { id: 4013, day: 4, no: 13, word: 'trail', meaning: 'v. 추적하다; 끌다, 끌리다 n. 자국, 흔적; 오솔길', memo: 'trail(질질 끌다/자국) → 땅에 난 자국이나 길을 따라가다 💡 발자국을 추적하다.' },
  { id: 4014, day: 4, no: 14, word: 'strict', meaning: 'a. 엄격한, 엄한; 정확한, 엄밀한', memo: 'strict(팽팽하게 죄는) → 규율을 팽팽하게 조여 엄하게 다스리다 💡 엄격한 규칙.' },
  { id: 4015, day: 4, no: 15, word: 'restrict', meaning: 'v. 제한하다, 한정하다', memo: 're(다시/뒤에) + strict(죄다) → 행동의 범위를 팽팽하게 죄어 가두다 💡 출입을 제한하다.' },
  { id: 4016, day: 4, no: 16, word: 'strain', meaning: 'n. 부담, 압력, 압박 v. 잡아당기다, 긴장시키다', memo: 'strain(팽팽하게 당기다) → 근육이나 마음을 팽팽하게 당겨 부담을 주다 💡 심리적 긴장.' },
  { id: 4017, day: 4, no: 17, word: 'restrain', meaning: 'v. 억제하다, 제지하다', memo: 're(뒤로) + strain(당기다) → 앞으로 가려는 것을 뒤로 팽팽하게 잡아당겨 말리다 💡 감정을 억제하다.' },
  { id: 4018, day: 4, no: 18, word: 'constrain', meaning: 'v. 제한하다, 강요하다', memo: 'con(함께/강하게) + strain(죄다) → 꽁꽁 묶어 행동을 제한하거나 강요하다 💡 억지로 강요하다.' },
  { id: 4019, day: 4, no: 19, word: 'propel', meaning: 'v. 추진하다, 나아가게 하다', memo: 'pro(앞으로) + pel(몰다) → 앞으로 힘껏 몰아붙이다 💡 로켓을 추진하다.' },
  { id: 4020, day: 4, no: 20, word: 'compel', meaning: 'v. 강요[강제]하다, 억지로 ~하게 하다', memo: 'com(강하게) + pel(몰다) → 강한 힘으로 억지로 몰아붙이다 💡 자백을 강요하다.' },
  { id: 4021, day: 4, no: 21, word: 'expel', meaning: 'v. 쫓아내다, 추방하다', memo: 'ex(밖으로) + pel(몰다) → 조직 밖으로 강제로 몰아내다 💡 학생을 퇴학시키다.' },
  { id: 4022, day: 4, no: 22, word: 'pulse', meaning: 'n. 맥박 v. 맥박이 뛰다', memo: 'pulse(뛰다/고동치다) → 심장이 두근두근 뛰는 박동 💡 빠른 맥박.' },
  { id: 4023, day: 4, no: 23, word: 'impulse', meaning: 'n. 충동, 자극; 추진(력)', memo: 'im(안으로) + pulse(치다) → 마음속을 쿵 치고 지나가는 충동 💡 충동적인 구매.' },
  { id: 4024, day: 4, no: 24, word: 'involve', meaning: 'v. 포함하다, 수반하다; 관련시키다', memo: 'in(안에) + volve(굴리다) → 사건 속에 함께 휘말려 들어가게 하다 💡 사건에 연루시키다.' },
  { id: 4025, day: 4, no: 25, word: 'evolve', meaning: 'v. 진화하다[시키다], 발전하다[시키다]', memo: 'e(밖으로) + volve(굴려 나가다) → 단계별로 굴리며 발전해 나가다 💡 생물이 진화하다.' },
  { id: 4026, day: 4, no: 26, word: 'revolve', meaning: 'v. 회전하다, 돌다', memo: 're(제자리로) + volve(굴리다) → 주위를 둥글게 굴러 돌다 💡 지구가 태양 주위를 회전하다.' },
  { id: 4027, day: 4, no: 27, word: 'revolt', meaning: 'v. 반란을 일으키다, 반항하다 n. 반역, 반항', memo: 're(반대로) + volt(구르다/뒤집다) → 체제에 맞서 아래로 굴러엎어지다 💡 정부에 반란을 일으키다.' },
  { id: 4028, day: 4, no: 28, word: 'convert', meaning: 'v. 전환[개조]하다, 바꾸다', memo: 'con(완전히) + vert(돌리다) → 성질이나 형태를 완전히 돌려 바꾸다 💡 화폐를 환전하다.' },
  { id: 4029, day: 4, no: 29, word: 'divert', meaning: 'v. 방향을 전환하다; (주의를) 딴 데로 돌리다', memo: 'di(다른 곳으로) + vert(돌리다) → 흐름이나 시선을 다른 방향으로 돌리다 💡 주의를 딴 데로 돌리다.' },
  { id: 4030, day: 4, no: 30, word: 'introvert', meaning: 'n. 내향적인 사람 a. 내향적인', memo: 'intro(안으로) + vert(돌리다) → 관심이 자기 안쪽으로 향하는 사람 💡 내향적인 성격.' },
  { id: 4031, day: 4, no: 31, word: 'extrovert', meaning: 'n. 외향적인 사람 a. 외향적인', memo: 'extro(밖으로) + vert(돌리다) → 관심이 바깥쪽 세상으로 향하는 사람 💡 외향적인 사람.' },
  { id: 4032, day: 4, no: 32, word: 'reverse', meaning: 'v. 뒤집다, 거꾸로 하다 a. 반대의, 역의 n. 반대', memo: 're(뒤로) + verse(돌리다) → 앞뒤를 완전히 뒤로 돌려놓다 💡 순서를 거꾸로 하다.' },
  { id: 4033, day: 4, no: 33, word: 'converse', meaning: 'a. 반대반대의 n. 정반대 v. 대화하다', memo: 'con(함께) + verse(돌려 말하다) → 서로 말을 주고받거나 정반대 방향을 가리키다 💡 대화하다/반대의.' },
  { id: 4034, day: 4, no: 34, word: 'inverse', meaning: 'a. 역의, 반대의 n. 정반대', memo: 'in(안으로/반대로) + verse(돌리다) → 순서나 위치가 정반대로 뒤집힌 💡 역의 관계.' },
  { id: 4035, day: 4, no: 35, word: 'diverge', meaning: 'v. 나뉘다, 갈라지다; 벗어나다, 이탈하다', memo: 'di(벌어져) + verge(향하다) → 길이나 생각이 서로 다른 방향으로 갈라지다 💡 의견이 갈라지다.' },
  { id: 4036, day: 4, no: 36, word: 'converge', meaning: 'v. 모이다, 수렴되다', memo: 'con(함께) + verge(향하다) → 한곳을 향하여 다 함께 모여들다 💡 한 점으로 모이다.' },
  { id: 4037, day: 4, no: 37, word: 'controversy', meaning: 'n. 논쟁', memo: 'contro(반대로) + vers(돌리다) + y → 찬반 양론이 서로 맞서 팽팽하게 돌다 💡 치열한 논쟁.' },
  { id: 4038, day: 4, no: 38, word: 'versatile', meaning: 'a. 다재다능한; 다용도의', memo: 'vers(돌리다) + atile(~하기 쉬운) → 이리저리 상황에 맞춰 팔방미인으로 잘 돌변하는 💡 다재다능한 재능.' },
  { id: 4039, day: 4, no: 39, word: 'fluid', meaning: 'n. 유동체[액체, 기체] a. 유동적인, 변하기 쉬운', memo: 'flu(흐르다) + id → 물처럼 자유롭게 흐르는 성질의 것 💡 유동적인 상황.' },
  { id: 4040, day: 4, no: 40, word: 'fluent', meaning: 'a. 유창한, 능변의', memo: 'flu(흐르다) + ent → 말이 막힘없이 물 흐르듯 술술 나오는 💡 유창한 영어 실력.' },
  { id: 4041, day: 4, no: 41, word: 'affluent', meaning: 'a. 풍부한, 부유한', memo: 'af(~로) + flu(흐르다) + ent → 재물이 내 앞으로 강물처럼 넘쳐흐르는 💡 부유한 가정.' },
  { id: 4042, day: 4, no: 42, word: 'fluctuate', meaning: 'v. 오르내리다, 변동하다', memo: 'fluct(흐르다/출렁이다) + uate → 물결이 출렁이듯 위아래로 흔들리다 💡 가격이 오르내리다.' },
  { id: 4043, day: 4, no: 43, word: 'admit', meaning: 'v. 인정하다, 받아들이다; (입학을) 허가하다', memo: 'ad(~쪽으로) + mit(보내다) → 진실이나 사람을 안으로 들여보내 받아들이다 💡 잘못을 인정하다.' },
  { id: 4044, day: 4, no: 44, word: 'submit', meaning: 'v. 제출하다; 복종하다, 굴복하다', memo: 'sub(아래로) + mit(보내다) → 서류를 아래로 건네거나 상전 아래로 고개를 숙이다 💡 서류를 제출하다.' },
  { id: 4045, day: 4, no: 45, word: 'transmit', meaning: 'v. 전송하다, (열 등을) 전도하다; 전염시키다', memo: 'trans(넘어) + mit(보내다) → 신호나 열을 저쪽 편으로 멀리 보내다 💡 데이터를 전송하다.' },
  { id: 4046, day: 4, no: 46, word: 'commit', meaning: 'v. (범죄·실수 등을) 저지르다; 전념하다, 헌신하다; 맡기다, 위임하다', memo: 'com(완전히) + mit(맡기다/빠지다) → 마음이나 몸을 완전히 던져 몰두하거나 저지르다 💡 죄를 저지르다.' },
  { id: 4047, day: 4, no: 47, word: 'emit', meaning: 'v. 내뿜다, 방출하다', memo: 'e(밖으로) + mit(보내다) → 빛이나 가스를 바깥으로 뿜어내다 💡 가스를 방출하다.' },
  { id: 4048, day: 4, no: 48, word: 'intermittent', meaning: 'a. 간헐적인, 간간이 일어나는', memo: 'inter(사이에) + mit(보내다) + tent → 중간중간에 신호를 끊었다가 보내다 💡 간헐적인 비.' },
  { id: 4049, day: 4, no: 49, word: 'mission', meaning: 'n. 임무, 사명; 전도, 포교; 사절단', memo: 'miss(보내다) + ion → 특별한 목적을 가지고 파견된 임무 💡 중요한 임무.' },
  { id: 4050, day: 4, no: 50, word: 'dismiss', meaning: 'v. 해고하다; 해산시키다; 묵살하다', memo: 'dis(멀리) + miss(보내다) → 사람이나 생각을 멀리 쫓아버리다 💡 직원을 해고하다.' },
  { id: 5001, day: 5, no: 1, word: 'tend', meaning: 'v. ~하는 경향이 있다, ~하기 쉽다; 돌보다', memo: 'tend(향하다) → 마음이나 시선이 어느 한쪽으로 향해 기울다 💡 ~하는 경향이 있다.' },
  { id: 5002, day: 5, no: 2, word: 'extend', meaning: 'v. 확장[연장]하다, 늘리다', memo: 'ex(밖으로) + tend(뻗다) → 공간이나 범위를 바깥쪽으로 쭉 뻗어 늘리다 💡 기간을 연장하다.' },
  { id: 5003, day: 5, no: 3, word: 'intend', meaning: 'v. ~할 작정이다, 의도하다; 의미하다', memo: 'in(안에) + tend(마음을 두다) → 마음속에 어떤 목표를 품다 💡 의도하다.' },
  { id: 5004, day: 5, no: 4, word: 'pretend', meaning: 'v. ~인 체하다, 가장하다', memo: 'pre(앞세워) + tend(척하다) → 겉으로 앞세워 실제인 것처럼 늘어놓다 💡 모르는 체하다.' },
  { id: 5005, day: 5, no: 5, word: 'tense', meaning: 'a. 긴장한; 팽팽한', memo: 'tens(팽팽하게 당기다) → 활시위를 팽팽하게 잡아당긴 상태 💡 긴장된 분위기.' },
  { id: 5006, day: 5, no: 6, word: 'infinite', meaning: 'a. 무한한, 한계가 없는', memo: 'in(아님) + fin(끝/한계) + ite → 끝이나 한계가 전혀 없는 💡 무한한 우주.' },
  { id: 5007, day: 5, no: 7, word: 'define', meaning: 'v. 정의하다, 규정하다', memo: 'de(완전히) + fin(경계를 짓다) → 테두리를 완전히 쳐서 명확히 구분 짓다 💡 개념을 정의하다.' },
  { id: 5008, day: 5, no: 8, word: 'confine', meaning: 'v. 제한하다, 한정하다; 가두다, 감금하다', memo: 'con(함께) + fin(테두리) → 일정한 테두리 안에 꽁꽁 가두어 제한하다 💡 행동을 제한하다.' },
  { id: 5009, day: 5, no: 9, word: 'refine', meaning: 'v. 정제하다, 불순물을 제거하다; 다듬다, 세련되게 하다', memo: 're(다시) + fine(좋게 만들다) → 불순물을 걸러내어 다시 말끔하게 다듬다 💡 원유를 정제하다.' },
  { id: 5010, day: 5, no: 10, word: 'structure', meaning: 'n. 건축, 건물; 구조 v. 조직하다, 구조화하다', memo: 'struct(짓다) + ure(명사미) → 단단하게 지어진 건물이나 조직의 뼈대 💡 건물의 구조.' },
  { id: 5011, day: 5, no: 11, word: 'construct', meaning: 'v. 건설하다, 세우다; 구성하다', memo: 'con(함께) + struct(쌓아 올리다) → 벽돌 등을 함께 쌓아 올려 건물을 짓다 💡 다리를 건설하다.' },
  { id: 5012, day: 5, no: 12, word: 'instruct', meaning: 'v. 가르치다, 교육하다; 지시하다', memo: 'in(안에) + struct(구조를 짜넣다) → 머릿속에 지식의 뼈대를 차곡차곡 넣어주다 💡 업무를 지시하다.' },
  { id: 5013, day: 5, no: 13, word: 'obstruct', meaning: 'v. 방해하다, 막다', memo: 'ob(대항하여) + struct(가로막다) → 길목에 건물을 세워 통행을 막아버리다 💡 시야를 방해하다.' },
  { id: 5014, day: 5, no: 14, word: 'instrument', meaning: 'n. 도구, 기계; 악기', memo: 'in(안에) + struct(만들다) + ment → 정교하게 손으로 다루어 쓰는 도구 💡 정밀 의료 기기.' },
  { id: 5015, day: 5, no: 15, word: 'stable', meaning: 'a. 안정된, 견고한', memo: 'sta(서다) + able → 튼튼하게 잘 서 있어서 흔들림 없는 💡 경제적 안정.' },
  { id: 5016, day: 5, no: 16, word: 'static', meaning: 'a. 정적인, 고정적인', memo: 'stat(제자리에 서 있는) + ic → 움직이지 않고 한곳에 멈춰 선 💡 정적인 상태.' },
  { id: 5017, day: 5, no: 17, word: 'state', meaning: 'n. 상태; 국가 v. 진술하다, 말하다', memo: 'state(서 있는 상태) → 사물이 놓인 형편이나 나라의 공식 입장 💡 사실을 진술하다.' },
  { id: 5018, day: 5, no: 18, word: 'status', meaning: 'n. (사회적) 지위, 신분; 상황', memo: 'stat(서다) + us → 사회 속에서 개인이 굳건히 서 있는 위치 💡 사회적 지위.' },
  { id: 5019, day: 5, no: 19, word: 'statue', meaning: 'n. 상, 조각상', memo: 'stat(서 있다) + ue → 광장이나 공원에 우뚝 서 있는 동상 💡 동상 조각.' },
  { id: 5020, day: 5, no: 20, word: 'constitute', meaning: 'v. 이루다, 구성[형성]하다', memo: 'con(함께) + stit(세우다) + ute → 여럿이 함께 모여 전체를 반듯이 세우다 💡 위원회를 구성하다.' },
  { id: 5021, day: 5, no: 21, word: 'substitute', meaning: 'v. 대신하다, 대체하다 n. 대신하는 것[사람]', memo: 'sub(아래에서) + stit(대기하다) + ute → 주전 선수 아래에서 대기하다가 교체 투입되다 💡 대체 선수.' },
  { id: 5022, day: 5, no: 22, word: 'institute', meaning: 'n. ~(부)국/청; 기관[협회], 연구소 v. 제정하다, 설립하다', memo: 'in(안에) + stit(세우다) + ute → 연구 목적의 건물을 안쪽에 반듯이 세우다 💡 연구소를 설립하다.' },
  { id: 5023, day: 5, no: 23, word: 'obstinate', meaning: 'a. 고집 센, 완고한', memo: 'ob(맞서서) + stin(서다) + ate → 자기 고집대로 끝까지 버티며 안 굽히는 💡 고집 센 태도.' },
  { id: 5024, day: 5, no: 24, word: 'consistent', meaning: 'a. 일관된; ~와 일치하는 (with)', memo: 'con(함께) + sist(서다) + ent → 쭉 한결같이 같은 자리에 서서 변함없는 💡 일관된 주장.' },
  { id: 5025, day: 5, no: 25, word: 'president', meaning: 'n. 대통령, 장, 회장', memo: 'pre(앞에) + sid(앉다) + ent → 모임이나 국가의 맨 앞자리에 앉는 우두머리 💡 공화국 대통령.' },
  { id: 5026, day: 5, no: 26, word: 'residue', meaning: 'n. 잔여, 나머지', memo: 're(뒤에) + sid(남아 있다) + ue → 다 쓰고 난 뒤에 뒤에 가라앉아 남은 것 💡 화학 약품 잔여물.' },
  { id: 5027, day: 5, no: 27, word: 'sedentary', meaning: 'a. 주로 앉아서 하는', memo: 'sed(앉다) + entary(형용사미) → 종일 의자에 엉덩이를 붙이고 앉아 있는 💡 책상앞에 앉아있는 업무.' },
  { id: 5028, day: 5, no: 28, word: 'session', meaning: 'n. 시간, 기간, 과정, 학기', memo: 'sess(앉아 있는 시간) → 의회나 학교에서 모여서 회의나 수업을 하는 기간 💡 국회 회기.' },
  { id: 5029, day: 5, no: 29, word: 'assess', meaning: 'v. 평가하다, 진단하다', memo: 'as(곁에) + sess(앉다) → 세금을 매기기 위해 옆에 앉아 꼼꼼히 살피다 💡 가치를 평가하다.' },
  { id: 5030, day: 5, no: 30, word: 'pesticide', meaning: 'n. 살충제, 농약', memo: 'pest(해충) + cide(죽이다) → 해충을 죽이기 위해 뿌리는 약품 💡 농작물 살충제.' },
  { id: 5031, day: 5, no: 31, word: 'suicide', meaning: 'n. 자살 v. 자살하다', memo: 'sui(스스로) + cide(죽이다) → 스스로 자기 자신을 목숨 끊는 행위 💡 비극적 자살.' },
  { id: 5032, day: 5, no: 32, word: 'homicide', meaning: 'n. 살인', memo: 'homo(사람) + cide(죽이다) → 다른 사람의 목숨을 해치는 범죄 💡 살인 사건.' },
  { id: 5033, day: 5, no: 33, word: 'precise', meaning: 'a. 정밀한, 정확한', memo: 'pre(미리) + cise(자르다) → 오차 없이 정확하게 딱 맞도록 잘라 만든 💡 정밀한 측정.' },
  { id: 5034, day: 5, no: 34, word: 'severe', meaning: 'a. 극심한, 심각한; 엄격한', memo: 'severe(거친/혹독한) → 바람이나 상황이 가혹하게 몰아치는 💡 극심한 고통.' },
  { id: 5035, day: 5, no: 35, word: 'segment', meaning: 'n. 부분, 구획, 조각 v. 나누다, 분할하다', memo: 'seg(자르다) + ment → 커다란 덩어리를 싹둑 잘라낸 한 조각 💡 시장 세그먼트.' },
  { id: 5036, day: 5, no: 36, word: 'intersect', meaning: 'v. 가로지르다, 교차하다', memo: 'inter(사이에) + sect(자르다/지나가다) → 두 길이 서로 가로질러 만나다 💡 교차로.' },
  { id: 5037, day: 5, no: 37, word: 'fragile', meaning: 'a. 약한, 부서지기 쉬운', memo: 'frag(부수다) + ile(~하기 쉬운) → 살짝만 건드려도 쉽게 바스러지는 💡 깨지기 쉬운 유리.' },
  { id: 5038, day: 5, no: 38, word: 'fragment', meaning: 'n. 조각, 파편 v. 산산이 부수다, 해체하다', memo: 'frag(부수다) + ment → 단단한 물체가 깨져서 흩어진 작은 조각 💡 도자기 파편.' },
  { id: 5039, day: 5, no: 39, word: 'fraction', meaning: 'n. 일부분, 단편; 분수, 비율', memo: 'fract(부수다) + ion → 전체를 잘게 부순 일부분 💡 아주 적은 분량.' },
  { id: 5040, day: 5, no: 40, word: 'fracture', meaning: 'n. 골절, 파손 v. 골절되다, 파열되다', memo: 'fract(부수다) + ure → 뼈나 단단한 물체가 뚝 부러짐 💡 다리 골절.' },
  { id: 5041, day: 5, no: 41, word: 'bankrupt', meaning: 'a. 파산한, 지급 불능의 v. 파산시키다', memo: 'bank(탁자) + rupt(깨다) → 돈을 내어주던 은행 탁자가 박살 나서 돈이 다 떨어진 💡 기업 파산.' },
  { id: 5042, day: 5, no: 42, word: 'interrupt', meaning: 'v. 방해하다, 중단시키다', memo: 'inter(사이에) + rupt(깨뜨리다) → 말이나 행동의 흐름 사이에 불쑥 끼어들어 깨다 💡 회의를 중단시키다.' },
  { id: 5043, day: 5, no: 43, word: 'corrupt', meaning: 'a. 부패한, 타락한 v. 타락시키다, 부패하게 하다', memo: 'cor(완전히) + rupt(박살내다) → 도덕성이 완전히 박살 나 썩어 문드러진 💡 부패한 정치인.' },
  { id: 5044, day: 5, no: 44, word: 'erupt', meaning: 'v. 분출하다[시키다], 폭발하다[시키다]', memo: 'e(밖으로) + rupt(터지다) → 화산재나 용암이 밖으로 쾅 터져 나오다 💡 화산 폭발.' },
  { id: 5045, day: 5, no: 45, word: 'disrupt', meaning: 'v. 붕괴시키다, 파괴하다; 방해하다, 중단시키다', memo: 'dis(이리저리) + rupt(깨뜨리다) → 질서나 체제를 이리저리 부수어 혼란에 빠뜨리다 💡 시장을 교란하다.' },
  { id: 5046, day: 5, no: 46, word: 'abrupt', meaning: 'a. 갑작스러운, 돌연한', memo: 'ab(기조에서 벗어나) + rupt(터지다) → 예고 없이 갑자기 툭 튀어나오다 💡 갑작스러운 변화.' },
  { id: 5047, day: 5, no: 47, word: 'similar', meaning: 'a. 유사한, 비슷한', memo: 'simil(같다) + ar → 모양이나 성질이 서로 비슷하게 닮은 💡 비슷한 외모.' },
  { id: 5048, day: 5, no: 48, word: 'simulate', meaning: 'v. 가장하다, 흉내 내다; 모의실험을 하다', memo: 'simul(비슷하게) + ate → 실제 상황과 똑같이 흉내 내어 꾸미다 💡 비행 시뮬레이션.' },
  { id: 5049, day: 5, no: 49, word: 'simultaneous', meaning: 'a. 동시의, 동시에 일어나나는', memo: 'simul(동시에) + taneous → 시간 간격 없이 딱 맞춰 동시에 발생하는 💡 동시 통역.' },
  { id: 5050, day: 5, no: 50, word: 'assimilate', meaning: 'v. 동화되다[시키다]; 이해하다; 소화하다, 흡수하다', memo: 'as(~에) + simil(같게 하다) + ate → 남의 문화나 지식을 내 것으로 똑같이 소화 흡수하다 💡 사회에 동화되다.' },
  { id: 6001, day: 6, no: 1, word: 'generate', meaning: 'v. 만들어 내다, 발생시키다', memo: 'gener(생기게 하다) + ate → 새로운 에너지를 발생시켜 만들어내다 💡 전기를 발생시키다.' },
  { id: 6002, day: 6, no: 2, word: 'general', meaning: 'v. 일반적인, 보편적인 n. 장군', memo: 'gener(전체/종족) + al → 전체를 아우르는 일반적인 성격 💡 일반적인 경향.' },
  { id: 6003, day: 6, no: 3, word: 'generous', meaning: 'v. 관대한, 너그러운', memo: 'gener(베풀다) + ous → 베푸는 성향이 넘쳐 남에게 너그러운 💡 관대한 마음씨.' },
  { id: 6004, day: 6, no: 4, word: 'genetic', meaning: 'v. 유전의, 유전학의', memo: 'gene(유전자) + tic → 유전과 관련된 생물학적 특성 💡 유전적 요인.' },
  { id: 6005, day: 6, no: 5, word: 'genuine', meaning: 'v. 진짜의, 진정의; 성실한', memo: 'gen(태어나다/본성) + uine → 태생 그대로의 진짜 순수한 것 💡 진짜 가죽 제품.' },
  { id: 6006, day: 6, no: 6, word: 'ingenious', meaning: 'v. 기발한, 독창적인', memo: 'in(안에) + gen(천재적 재능) + ious → 머릿속에서 독창적인 아이디어가 번뜩이다 💡 기발한 해결책.' },
  { id: 6007, day: 6, no: 7, word: 'indigenous', meaning: 'v. 토착의, (그 지역) 고유의; 타고난', memo: 'indi(안에) + gen(나다) + ous → 그 지역 땅에서 태어나 자란 고유의 💡 토착 원주민.' },
  { id: 6008, day: 6, no: 8, word: 'novel', meaning: 'v. 참신한, 새로운 n. 소설', memo: 'nov(새로운) + el → 지금까지 보지 못한 완전히 새로운 이야기 💡 참신한 아이디어.' },
  { id: 6009, day: 6, no: 9, word: 'novice', meaning: 'v. 초보자, 풋내기', memo: 'nov(새로운) + ice → 이제 막 새로 시작한 서툰 사람 💡 운전 면허 초보자.' },
  { id: 6010, day: 6, no: 10, word: 'innovation', meaning: 'v. 혁신', memo: 'in(안에) + nov(새롭게 하다) + ation → 기존 틀을 완전히 새롭게 바꾸어 쇄신함 💡 기술 혁신.' },
  { id: 6011, day: 6, no: 11, word: 'renovate', meaning: 'v. 개조하다, 수리[보수]하다', memo: 're(다시) + nov(새롭게) + ate → 낡은 건물을 다시 새것처럼 싹 고치다 💡 주택을 개조하다.' },
  { id: 6012, day: 6, no: 12, word: 'renew', meaning: 'v. 갱신[연장]하다; 재개하다', memo: 're(다시) + new(새로운) → 계약 기간을 다시 새롭게 늘리다 💡 계약을 갱신하다.' },
  { id: 6013, day: 6, no: 13, word: 'medium', meaning: 'v. 매개물, 매체, 수단; 중간 a. 중간의', memo: 'medi(중간) + um → 양쪽 사이를 이어주는 중간 매개체 💡 정보 전달 매체.' },
  { id: 6014, day: 6, no: 14, word: 'mediate', meaning: 'v. 중재하다, 조정하다', memo: 'medi(중간에) + ate → 분쟁의 한가운데에 들어가 양측을 화해시키다 💡 협상을 중재하다.' },
  { id: 6015, day: 6, no: 15, word: 'meditate', meaning: 'v. 명상하다, 숙고하다', memo: 'med(마음을 중심에 두다) + ite → 잡념을 비우고 깊은 생각에 잠기다 💡 마음을 가다듬는 명상.' },
  { id: 6016, day: 6, no: 16, word: 'mediocre', meaning: 'v. 보통의, 평범한, 그저 그런', memo: 'medi(중간) + ocre(산 중턱) → 산 중간쯤에 걸쳐 있어 특출나지 않은 💡 평범한 실력.' },
  { id: 6017, day: 6, no: 17, word: 'Mediterranean', meaning: 'v. 지중해의', memo: 'medi(중간) + terr(땅) + anean → 대륙들 한가운데에 둘러싸인 바다 💡 지중해 연안.' },
  { id: 6018, day: 6, no: 18, word: 'meantime', meaning: 'v. 그동안 ad. 그동안에, 한편', memo: 'mean(중간의) + time(시간) → 그 사이에 일어나는 동안 💡 그동안에 일어난 일.' },
  { id: 6019, day: 6, no: 19, word: 'amid', meaning: 'v. prep. ~의 한복판에, ~이 한창일 때에', memo: 'a(에) + mid(중간) → 복잡한 상황이나 한가운데에 쏙 파묻혀 💡 혼란 속의 한복판.' },
  { id: 6020, day: 6, no: 20, word: 'vacant', meaning: 'v. a. 비어 있는, 공석인', memo: 'vac(비우다) + ant → 안에 아무도 없이 텅 비어 있는 방 💡 공석인 자리.' },
  { id: 6021, day: 6, no: 21, word: 'vacuum', meaning: 'v. n. 진공 (상태)', memo: 'vac(비우다) + uum → 공기조차 없이 완전히 텅 빈 상태 💡 진공 청소기.' },
  { id: 6022, day: 6, no: 22, word: 'vague', meaning: 'v. a. 모호한, 애매한, 희미한', memo: 'vague(떠돌다/안개) → 윤곽이 뚜렷하지 않고 안개처럼 희미한 💡 모호한 답변.' },
  { id: 6023, day: 6, no: 23, word: 'vanish', meaning: 'v. 사라지다', memo: 'van(비우다/없애다) + ish → 눈앞에서 형태도 없이 말끔히 사라져 버리다 💡 마술처럼 사라지다.' },
  { id: 6024, day: 6, no: 24, word: 'vain', meaning: 'v. a. 헛된, 소용없는; 허영심이 많은', memo: 'vain(빈) → 속이 텅 비어 실속 없고 헛된 노력 💡 헛된 시도.' },
  { id: 6025, day: 6, no: 25, word: 'evaporate', meaning: 'v. 증발하다, 증발시키다', memo: 'e(밖으로) + vapor(증기) + ate → 액체가 증기 형태로 밖으로 날아가다 💡 수분이 증발하다.' },
  { id: 6026, day: 6, no: 26, word: 'evacuate', meaning: 'v. 대피시키다; 비우다', memo: 'e(밖으로) + vac(비우다) + uate → 위험 지역의 사람들을 밖으로 내보내 비우다 💡 주민 대피.' },
  { id: 6027, day: 6, no: 27, word: 'devastate', meaning: 'v. 완전히 파괴하다; 망연자실케 하다', memo: 'de(완전히) + vast(황폐하게) + ate → 온통 사방을 쑥대밭으로 완전히 파괴하다 💡 도시를 초토화하다.' },
  { id: 6028, day: 6, no: 28, word: 'humanity', meaning: 'v. n. 인류; 인간성', memo: 'human(인간) + ity → 인간이 가진 본성이나 전체 인류 💡 인류의 미래.' },
  { id: 6029, day: 6, no: 29, word: 'humane', meaning: 'v. a. 자비로운, 인도적인', memo: 'human(인간적인) + e → 인간다운 따뜻한 마음씨를 베푸는 💡 인도적 차원의 지원.' },
  { id: 6030, day: 6, no: 30, word: 'humble', meaning: 'v. a. 겸손한; 보잘것없는', memo: 'hum(땅/낮은) + ble → 낮은 데 처해 자신을 낮추는 겸손함 💡 겸손한 태도.' },
  { id: 6031, day: 6, no: 31, word: 'humility', meaning: 'v. n. 겸손, 비하', memo: 'hum(낮은) + ility → 자신을 낮추는 태도와 성품 💡 겸손의 미덕.' },
  { id: 6032, day: 6, no: 32, word: 'humiliate', meaning: 'v. 굴욕감을 주다, 창피를 주다', memo: 'hum(낮추다) + ili + ate → 남의 자존심을 시궁창으로 낮추어 창피 주다 💡 공개적인 굴욕.' },
  { id: 6033, day: 6, no: 33, word: 'exhume', meaning: 'v. 발굴하다', memo: 'ex(밖으로) + hum(흙/땅) + ube → 땅속 무덤이나 흙에서 시신을 파내다 💡 유골을 발굴하다.' },
  { id: 6034, day: 6, no: 34, word: 'humid', meaning: 'v. a. 습기 있는, 눅눅한', memo: 'humid(축축한) → 공기 중에 물기가 많아 꿉꿉한 날씨 💡 습한 장마철.' },
  { id: 6035, day: 6, no: 35, word: 'manual', meaning: 'v. a. 손의; 수동의 n. 소책자, 설명서', memo: 'manu(손) + al → 손으로 직접 조작하거나 지침을 적은 책 💡 자동차 설명서.' },
  { id: 6036, day: 6, no: 36, word: 'manufacture', meaning: 'v. 생산하다, 제조하다 n. 제조(업)', memo: 'manu(손) + fact(만들다) + ure → 손이나 공장에서 물건을 대량으로 찍어내다 💡 공장 제품 생산.' },
  { id: 6037, day: 6, no: 37, word: 'manipulate', meaning: 'v. 잘 다루다; 조종[조작]하다', memo: 'manu(손) + pul(조종하다) + ate → 손으로 교묘하게 이리저리 주무르며 조작하다 💡 여론 조작.' },
  { id: 6038, day: 6, no: 38, word: 'maneuver', meaning: 'v. n. 책략, 술수; 작전, 전략적 움직임 v. (전략적으로) 이동시키다', memo: 'manu(손) + oeuvr(작업) → 손으로 교묘하게 판을 짜는 작전 💡 군사 기동 작전.' },
  { id: 6039, day: 6, no: 39, word: 'legal', meaning: 'v. a. 법률의, 법률상의; 합법적인', memo: 'leg(법) + al → 법의 테두리 안에 들어맞는 합법적인 💡 법적 절차.' },
  { id: 6040, day: 6, no: 40, word: 'legitimate', meaning: 'v. a. 합법적인, 정당한', memo: 'leg(법) + itimate → 법적으로 정당한 권리를 갖춘 💡 정당한 사유.' },
  { id: 6041, day: 6, no: 41, word: 'legislation', meaning: 'v. n. 법률의 제정, 입법 (행위)', memo: 'legislat(법을 만들다) + ion → 국회에서 새로운 법안을 통과시키는 입법 💡 입법 과정.' },
  { id: 6042, day: 6, no: 42, word: 'privilege', meaning: 'v. n. 특권, 특전 v. ~에게 특권을 주다', memo: 'privi(사적인) + lege(법) → 특정한 소수에게만 주어지는 사적인 특별 권리 💡 특권층의 혜택.' },
  { id: 6043, day: 6, no: 43, word: 'legacy', meaning: 'v. n. 유산', memo: 'leg(남기다) + acy → 선조가 후손들에게 물려준 재산이나 유산 💡 역사적 유산.' },
  { id: 6044, day: 6, no: 44, word: 'delegate', meaning: 'v. 위임하다 n. 대표, 대리인', memo: 'de(아래로) + leg(보내다) + ate → 권한이나 업무를 아랫사람에게 위임하여 보내다 💡 권한을 위임하다.' },
  { id: 6045, day: 6, no: 45, word: 'biology', meaning: 'v. n. 생물학', memo: 'bio(생명) + logy(학문) → 살아있는 생명체를 연구하는 학문 💡 대학 생물학.' },
  { id: 6046, day: 6, no: 46, word: 'sociology', meaning: 'v. n. 사회학', memo: 'socio(사회) + logy(학문) → 인간이 모여 사는 사회 현상을 연구하는 학문 💡 현대 사회학.' },
  { id: 6047, day: 6, no: 47, word: 'psychology', meaning: 'v. n. 심리학; 심리 (상태)', memo: 'psycho(마음) + logy(학문) → 인간의 마음과 행동 양식을 연구하는 학문 💡 범죄 심리학.' },
  { id: 6048, day: 6, no: 48, word: 'ecology', meaning: 'v. n. 생태학; 생태계', memo: 'eco(환경/집) + logy(학문) → 생물과 환경 간의 상호 관계를 연구하는 학문 💡 생태계 보호.' },
  { id: 6049, day: 6, no: 49, word: 'geology', meaning: 'v. n. 지질학', memo: 'geo(지구/땅) + logy(학문) → 지구의 구조와 암석을 연구하는 지질학 💡 지질 조사.' },
  { id: 6050, day: 6, no: 50, word: 'anthropology', meaning: 'v. n. 인류학', memo: 'anthrop(인간) + ology(학문) → 인간의 진화와 문화를 연구하는 인류학 💡 문화 인류학.' },
  { id: 7001, day: 7, no: 1, word: 'comply', meaning: 'v. (법·명령 등에) 따르다, 준수하다 (with)', memo: 'com(완전히) + ply(채우다) → 요구사항을 완전히 채워주다 💡 상대 요구에 맞춰 따르다/준수하다.' },
  { id: 7002, day: 7, no: 2, word: 'imply', meaning: 'v. 내포하다, 암시하다', memo: 'im(안에) + ply(접다) → 마음속에 뜻을 겹겹이 접어 숨겨두다 💡 의미를 내포하다.' },
  { id: 7003, day: 7, no: 3, word: 'implicit', meaning: 'a. 함축적인, 암시적인', memo: 'im(안에) + plic(접다) + it → 겉으로 드러내지 않고 마음속에 접어 둔 💡 함축적인 의미.' },
  { id: 7004, day: 7, no: 4, word: 'explicit', meaning: 'a. 명백한, 분명한', memo: 'ex(밖으로) + plic(접은 것을 펴다) → 접힌 것을 밖으로 쫙 펼쳐 보여주다 💡 명백한 설명.' },
  { id: 7005, day: 7, no: 5, word: 'implication', meaning: 'n. 연관, 연루; 함축, 암시; 영향, 결과', memo: 'imply의 명사형 → 말 속에 접혀 있는 숨은 뜻과 파장 💡 사건의 연루와 영향.' },
  { id: 7006, day: 7, no: 6, word: 'complicate', meaning: 'v. 복잡하게 만들다', memo: 'com(함께) + plic(얽히게 하다) + ate → 실타래를 사방으로 복잡하게 얽히게 만들다 💡 일을 복잡하게 하다.' },
  { id: 7007, day: 7, no: 7, word: 'explicate', meaning: 'v. 설명하다, 명백하게 하다', memo: 'ex(밖으로) + plic(풀어내다) + ate → 복잡하게 꼬인 것을 밖으로 깔끔하게 풀어 설명하다 💡 이론을 설명하다.' },
  { id: 7008, day: 7, no: 8, word: 'duplicate', meaning: 'v. 복사하다, 복제하다 a. 복사의, 복제의 n. 복사본, 복제품', memo: 'du(둘로) + plic(접다/겹치다) → 원본과 똑같이 두 개로 겹쳐서 만들다 💡 문서를 복사하다.' },
  { id: 7009, day: 7, no: 9, word: 'replicate', meaning: 'v. 복제하다', memo: 're(다시) + plic(겹치다) → 원본과 똑같이 다시 한 번 그대로 재현하다 💡 세포를 복제하다.' },
  { id: 7010, day: 7, no: 10, word: 'deplete', meaning: 'v. 고갈시키다', memo: 'de(아래로/완전히) + plet(채우다) → 창고의 물건을 싹 비워 바닥을 드러내다 💡 자원을 고갈시키다.' },
  { id: 7011, day: 7, no: 11, word: 'devour', meaning: 'v. 게걸스레 먹다, 탐닉하다', memo: 'de(완전히) + vour(삼키다) → 음식이나 책을 허겁지겁 완전히 삼켜버리다 💡 책을 탐닉하다.' },
  { id: 7012, day: 7, no: 12, word: 'herbivorous', meaning: 'a. 초식성의', memo: 'herbi(풀) + vor(먹다) + ous → 풀을 뜯어먹고 사는 성질의 💡 초식 동물.' },
  { id: 7013, day: 7, no: 13, word: 'carnivorous', meaning: 'a. 육식성의', memo: 'carni(고기) + vor(먹다) + ous → 고기를 먹고 사는 성질의 💡 육식 동물.' },
  { id: 7014, day: 7, no: 14, word: 'omnivorous', meaning: 'a. 잡식성의; 다방면의', memo: 'omni(모든) + vor(먹다) + ous → 가리지 않고 모든 것을 다 잘 먹는 💡 잡식성 식습관.' },
  { id: 7015, day: 7, no: 15, word: 'progress', meaning: 'n. 전진, 진행; 진보, 발전 v. 전진하다, 진행되다; 진보[발전]하다', memo: 'pro(앞으로) + gress(나아가다) → 목표를 향해 앞으로 성큼성큼 나아가다 💡 과학의 발전.' },
  { id: 7016, day: 7, no: 16, word: 'procedure', meaning: 'n. 절차, 순서', memo: 'pro(앞서) + ced(가다) + ure → 정해진 순서대로 차례차례 진행되는 절차 💡 업무 처리 절차.' },
  { id: 7017, day: 7, no: 17, word: 'prospect', meaning: 'n. 가망, 가능성; 전망, 예상', memo: 'pro(앞을) + spect(보다) → 다가올 미래의 풍경이나 가능성을 내다보다 💡 밝은 취업 전망.' },
  { id: 7018, day: 7, no: 18, word: 'provision', meaning: 'n. 대비, 준비; 공급, 제공; (법률) 규정, 조항', memo: 'pro(미리) + vis(보고) + ion → 미래를 내다보고 미리 준비하거나 마련해 둠 💡 비상 식량 대비.' },
  { id: 7019, day: 7, no: 19, word: 'prophecy', meaning: 'n. 예언', memo: 'pro(미리) + phe(말하다) + cy → 앞으로 일어날 일을 미리 내다보고 말해주다 💡 신비로운 예언.' },
  { id: 7020, day: 7, no: 20, word: 'predict', meaning: 'v. 예측하다, 예상하다', memo: 'pre(미리) + dict(말하다) → 미래의 일어날 일을 미리 짚어서 말하다 💡 날씨를 예측하다.' },
  { id: 7021, day: 7, no: 21, word: 'prevent', meaning: 'v. 막다, 방해하다; 예방하다', memo: 'pre(미리) + vent(오다) → 사고가 찾아오기 전에 미리 앞서서 차단하다 💡 사고를 예방하다.' },
  { id: 7022, day: 7, no: 22, word: 'present', meaning: 'v. 주다, 제시하다 n. 현재; 선물 a. 현재의; 출석한, 존재하는', memo: 'pre(앞에) + sent(존재하는) → 사람들 앞에 내놓아 건네주거나 현재에 존재하다 💡 의견을 제시하다.' },
  { id: 7023, day: 7, no: 23, word: 'prehistoric', meaning: 'a. 선사시대의', memo: 'pre(이전에) + historic(역사적인) → 문자로 기록된 역사 시대보다 훨씬 이전의 💡 선사 시대 유적.' },
  { id: 7024, day: 7, no: 24, word: 'premature', meaning: 'a. 시기상조의, 성급한; 조산의', memo: 'pre(너무 이른) + mature(성숙한) → 무르익기도 전에 너무 일찍 서두르는 💡 시기상조의 판단.' },
  { id: 7025, day: 7, no: 25, word: 'previous', meaning: 'a. 앞의, 이전의', memo: 'pre(앞에) + vius(길) → 걸어온 길의 바로 앞쪽에 위치한 💡 이전의 경험.' },
  { id: 7026, day: 7, no: 26, word: 'precaution', meaning: 'n. 예방 조치; 조심, 경계', memo: 'pre(미리) + caution(조심하다) → 위험에 대비해 미리 조심하고 경계함 💡 안전 예방 조치.' },
  { id: 7027, day: 7, no: 27, word: 'prejudice', meaning: 'n. 편견 v. 편견을 갖게 하다', memo: 'pre(미리) + jud(판단하다) + ice → 제대로 보기도 전에 미리 마음대로 판단해 버림 💡 인종적 편견.' },
  { id: 7028, day: 7, no: 28, word: 'prerequisite', meaning: 'n. 필요[전제] 조건 a. 필수의, 전제가 되는', memo: 'pre(미리) + requis(요구되는) + ite → 무언가를 하기에 앞서 미리 갖추어야 할 조건 💡 입학 필수 조건.' },
  { id: 7029, day: 7, no: 29, word: 'preoccupy', meaning: 'v. ~의 마음을 사로잡다, 몰두시키다; 먼저 차지하다, 선취하다', memo: 'pre(먼저) + occupy(잡다) → 생각이나 자리를 남보다 먼저 찜해서 사로잡다 💡 마음을 사로잡다.' },
  { id: 7030, day: 7, no: 30, word: 'premise', meaning: 'n. 전제', memo: 'pre(앞서) + mise(보내다/놓다) → 논리의 기초를 세우기 위해 맨 앞에 깔아두는 가정 💡 논리적 전제.' },
  { id: 7031, day: 7, no: 31, word: 'foresee', meaning: 'v. 예견하다, (앞을) 내다보다', memo: 'fore(미리/앞서) + see(보다) → 다가올 미래를 눈앞에 그려보듯 미리 내다보다 💡 위험을 예견하다.' },
  { id: 7032, day: 7, no: 32, word: 'foretell', meaning: 'v. 예언하다', memo: 'fore(미리) + tell(말하다) → 미래에 벌어질 일을 미리 귀띔해 주듯 말하다 💡 미래를 예언하다.' },
  { id: 7033, day: 7, no: 33, word: 'forecast', meaning: 'v. 예상[예측]하다, 예보하다 n. 예상[예측], 예보', memo: 'fore(미리) + cast(던지다) → 앞으로의 전망이나 수치를 미리 멀리 던져 예측하다 💡 일기 예보.' },
  { id: 7034, day: 7, no: 34, word: 'foremost', meaning: 'a. 가장 중요한, 맨 앞의, 최고의', memo: 'fore(맨 앞의) + most(최상) → 줄의 맨 앞자리에 서서 가장 으뜸가는 💡 가장 중요한 과제.' },
  { id: 7035, day: 7, no: 35, word: 'forehead', meaning: 'n. 이마', memo: 'fore(앞쪽) + head(머리) → 얼굴의 맨 위 앞쪽에 튀어나온 부위 💡 넓은 이마.' },
  { id: 7036, day: 7, no: 36, word: 'forerunner', meaning: 'n. 선구자, 전신', memo: 'fore(앞서) + runner(달리는 사람) → 다른 사람들보다 맨 앞에서 길을 개척하며 달리다 💡 시대의 선구자.' },
  { id: 7037, day: 7, no: 37, word: 'replace', meaning: 'v. 대신하다, 대체하다', memo: 're(다시) + place(제자리에 놓다) → 낡은 것을 치우고 새로운 것을 제자리에 다시 채우다 💡 부품을 교체하다.' },
  { id: 7038, day: 7, no: 38, word: 'remove', meaning: 'v. 제거하다', memo: 're(뒤로/떨어져) + move(움직이다) → 짐이나 방해물을 다른 곳으로 싹 치워버리다 💡 얼룩을 제거하다.' },
  { id: 7039, day: 7, no: 39, word: 'react', meaning: 'v. 반응하다, 반작용하다', memo: 're(다시/답하여) + act(행동하다) → 자극이 오면 그에 대응하여 되받아 행동하다 💡 약에 반응하다.' },
  { id: 7040, day: 7, no: 40, word: 'respond', meaning: 'v. 대응[대처]하다; 대답[응답]하다', memo: 're(답하여) + spond(약속하다/말하다) → 상대방의 물음에 맞추어 대답하고 대처하다 💡 질문에 응답하다.' },
  { id: 7041, day: 7, no: 41, word: 'recall', meaning: 'v. 기억해 내다, 상기하다; 회수하다 n. (제품) 리콜, 회수', memo: 're(다시) + call(부르다) → 기억 속의 정보를 다시 불러내거나 결함 제품을 불러들이다 💡 기억을 더듬다.' },
  { id: 7042, day: 7, no: 42, word: 'regain', meaning: 'v. 되찾다, 회복하다', memo: 're(다시) + gain(얻다) → 잃어버렸던 건강이나 지위를 다시 손에 넣다 💡 자존심을 되찾다.' },
  { id: 7043, day: 7, no: 43, word: 'reproduce', meaning: 'v. 다시 만들어 내다; 복사[복제]하다; 번식하다', memo: 're(다시) + produce(생산하다) → 똑같은 것을 다시 만들어 내거나 새 생명을 번식시키다 💡 개체 번식.' },
  { id: 7044, day: 7, no: 44, word: 're reassure', meaning: 'v. 안심시키다', memo: 're(다시) + assure(확신시키다) → 불안해하는 사람을 거듭 다독여 안심시키다 💡 불안감을 안심시키다.' },
  { id: 7045, day: 7, no: 45, word: 'retire', meaning: 'v. 은퇴하다, 물러나다', memo: 're(뒤로) + tire(방으로 들어가다) → 일선 현장에서 물러나 조용히 은퇴하다 💡 직장에서 정년 퇴직하다.' },
  { id: 7046, day: 7, no: 46, word: 'retrieve', meaning: 'v. 되찾다, 회수하다; 검색하다', memo: 're(다시) + trieve(찾아오다) → 잃어버린 데이터를 다시 찾아오거나 검색하다 💡 정보를 검색하다.' },
  { id: 7047, day: 7, no: 47, word: 'rejoice', meaning: 'v. 기뻐하다, 좋아하다', memo: 're(대단히) + joice(즐거워하다) → 마음속 깊이 우러나오는 기쁨으로 즐거워하다 💡 승리를 기뻐하다.' },
  { id: 7048, day: 7, no: 48, word: 'reciprocal', meaning: 'a. 상호 간의', memo: 're(로 서로) + ciprocal(주고받는) → 서로 주고받고 영향을 주고받는 관계 💡 상호 호혜적 협력.' },
  { id: 7049, day: 7, no: 49, word: 'reimburse', meaning: 'v. 정산[환급]하다, 배상하다', memo: 're(다시) + imburse(돈 주머니에 넣다) → 쓴 돈을 돌려주어 정산하거나 배상하다 💡 비용을 환급하다.' },
  { id: 7050, day: 7, no: 50, word: 'retreat', meaning: 'v. 물러나다, 후퇴하다 n. 후퇴', memo: 're(뒤로) + treat(가다) → 공격을 피해 뒤쪽으로 군사를 물리다 💡 적의 후퇴.' },
  { id: 8001, day: 8, no: 1, word: 'adopt', meaning: 'v. 채택하다; 입양하다', memo: 'ad( ~에) + opt(선택하다) → 마음에 드는 것을 골라서 내 아이나 제도로 받아들이다 💡 정책을 채택하다.' },
  { id: 8002, day: 8, no: 2, word: 'adapt', meaning: 'v. 맞추다, 조정[조절]하다; 적응하다; 각색하다, 개작하다', memo: 'ad( ~에) + apt(맞는) → 환경이나 조건에 딱 맞도록 알맞게 조절하다 💡 환경에 적응하다.' },
  { id: 8003, day: 8, no: 3, word: 'adjust', meaning: 'v. 맞추다, 조정[조절]하다; 적응하다', memo: 'ad( ~에) + just(바른) → 올바른 기준이나 위치에 딱 맞게 바로잡다 💡 시계를 맞추다.' },
  { id: 8004, day: 8, no: 4, word: 'adhere', meaning: 'v. 들러붙다, 부착하다 (to); 고수하다 (to)', memo: 'ad( ~에) + here(붙다) → 풀이나 끈끈이로 찰싹 달라붙게 만들다 💡 원칙을 고수하다.' },
  { id: 8005, day: 8, no: 5, word: 'admire', meaning: 'v. 존경하다, 감탄하며 바라보고', memo: 'ad( ~을 향해) + mire(놀라다) → 훌륭한 사람을 보고 감탄하며 우러러보다 💡 훌륭한 업적을 존경하다.' },
  { id: 8006, day: 8, no: 6, word: 'appoint', meaning: 'v. 임명[지명]하다; (시간·장소 등을) 정하다', memo: 'ap( ~에) + point(지정하다) → 특정한 자리나 시간에 꼭 집어서 정하다 💡 장관을 임명하다.' },
  { id: 8007, day: 8, no: 7, word: 'appease', meaning: 'v. 진정시키다, 달래다', memo: 'ap( ~로) + pease(평화) → 화난 사람에게 평화로운 상태가 되도록 달래주다 💡 화난 고객을 진정시키다.' },
  { id: 8008, day: 8, no: 8, word: 'assure', meaning: 'v. 확신시키다, 장담하다', memo: 'as( ~에게) + sure(확실한) → 상대방이 안심하도록 확실하게 장담해 주다 💡 결과를 확신시키다.' },
  { id: 8009, day: 8, no: 9, word: 'assort', meaning: 'v. 분류하다', memo: 'as( ~에) + sort(종류) → 제각기 알맞은 종류별로 묶어서 나누다 💡 물건을 종류별로 분류하다.' },
  { id: 8010, day: 8, no: 10, word: 'acknowledge', meaning: 'v. 인정하다, 시인하다; 감사하다', memo: 'ac( ~에) + knowledge(알고 있음) → 사실임을 알고 머리 숙여 받아들이거나 고마움을 표하다 💡 과오를 인정하다.' },
  { id: 8011, day: 8, no: 11, word: 'accord', meaning: 'v. 일치하다 (with) n. 일치, 합의', memo: 'ac( ~에) + cord(심장/마음) → 마음이 상대방과 똑같이 한곳으로 통하다 💡 의견이 일치하다.' },
  { id: 8012, day: 8, no: 12, word: 'affirm', meaning: 'v. 확인하다, 단언하다', memo: 'af( ~에) + firm(확고한) → 마음을 단단히 먹고 확실하게 그렇다고 힘주어 말하다 💡 사실임을 단언하다.' },
  { id: 8013, day: 8, no: 13, word: 'attach', meaning: 'v. 붙이다, 첨부하다', memo: 'at( ~에) + tach(못 박다/고정하다) → 서류나 물건을 딱 붙여서 고정하다 💡 사진을 첨부하다.' },
  { id: 8014, day: 8, no: 14, word: 'amass', meaning: 'v. 모으다, 축적하다', memo: 'a( ~로) + mass(더더기/무더기) → 돈이나 재산을 티끌 모아 큰 덩어리로 모으다 💡 부를 축적하다.' },
  { id: 8015, day: 8, no: 15, word: 'enable', meaning: 'v. ~할 수 있게 하다', memo: 'en( ~하게 하다) + able(가능한) → 어떤 일을 해낼 수 있는 능력을 부여하다 💡 성공할 수 있게 하다.' },
  { id: 8016, day: 8, no: 16, word: 'ensure', meaning: 'v. 확실하게 하다, 보장[보증]하다', memo: 'en( ~하게 하다) + sure(확실한) → 틀림없이 그렇게 되도록 확실하게 만들어 두다 💡 안전을 보장하다.' },
  { id: 8017, day: 8, no: 17, word: 'encourage', meaning: 'v. 격려하다; 장려하다, 권장하다', memo: 'en( ~안에) + courage(용기) → 마음속에 용기를 북돋워 주어 힘을 실어주다 💡 도전하도록 격려하다.' },
  { id: 8018, day: 8, no: 18, word: 'endanger', meaning: 'v. 위험에 빠뜨리다, 위태롭게 하다', memo: 'en( ~속으로) + danger(위험) → 위험한 상황 속으로 몰아넣다 💡 생명을 위태롭게 하다.' },
  { id: 8019, day: 8, no: 19, word: 'enlarge', meaning: 'v. 확대하다, 확장하다', memo: 'en( ~하게 하다) + large(큰) → 크기를 더 크게 부풀리거나 넓히다 💡 사진을 확대하다.' },
  { id: 8020, day: 8, no: 20, word: 'enrich', meaning: 'v. 부유하게 하다; 풍부하게 하다', memo: 'en( ~하게 하다) + rich(부유한/풍부한) → 질이나 양을 풍성하게 살찌우다 💡 지식을 풍부하게 하다.' },
  { id: 8021, day: 8, no: 21, word: 'entitle', meaning: 'v. 자격[권리]을 주다; 제목을 붙이다', memo: 'en( ~에게) + title(명칭/자격) → 정당한 권리나 타이틀을 부여하다 💡 투표권을 주다.' },
  { id: 8022, day: 8, no: 22, word: 'entrust', meaning: 'v. 위임하다, 맡기다', memo: 'en( ~에게) + trust(믿다) → 믿을 수 있는 사람에게 중요한 일을 맡겨 넘기다 💡 업무를 위임하다.' },
  { id: 8023, day: 8, no: 23, word: 'empower', meaning: 'v. 권한을 주다', memo: 'em( ~에게) + power(힘) → 공식적으로 힘과 권한을 실어주다 💡 권한을 위임하다.' },
  { id: 8024, day: 8, no: 24, word: 'enact', meaning: 'v. 제정하다', memo: 'en(만들다) + act(법률/행동) → 법률을 공식적으로 만들어 시행하다 💡 새 법안을 제정하다.' },
  { id: 8025, day: 8, no: 25, word: 'engross', meaning: 'v. 집중시키다, 몰두하게 만들다', memo: 'en(안으로) + gross(큰 덩어리) → 온 정신을 통째로 쏙 빼앗아 몰두하게 만들다 💡 독서에 몰두하다.' },
  { id: 8026, day: 8, no: 26, word: 'encompass', meaning: 'v. 포함하다, 아우르다; 에워싸다', memo: 'en(둘러싸다) + compass(나침반/범위) → 사방을 빙 둘러싸거나 전체를 포괄하다 💡 전 범위를 아우르다.' },
  { id: 8027, day: 8, no: 27, word: 'encode', meaning: 'v. 암호화[부호화]하다', memo: 'en(만들다) + code(암호) → 데이터를 해독하기 힘든 암호 형태로 바꾸다 💡 비밀번호를 암호화하다.' },
  { id: 8028, day: 8, no: 28, word: 'enlighten', meaning: 'v. 이해시키다, 계몽[교화]하다', memo: 'en(하게 하다) + light(빛) → 무지한 어둠 속에 있는 사람에게 빛을 비추어 깨우치다 💡 진실을 이해시키다.' },
  { id: 8029, day: 8, no: 29, word: 'embody', meaning: 'v. 구체화하다, 구현하다', memo: 'em(만들다) + body(몸) → 추상적인 생각을 눈에 보이는 실체(몸)로 드러내다 💡 이념을 구현하다.' },
  { id: 8030, day: 8, no: 30, word: 'communicate', meaning: 'v. 의사소통하다; 전하다, 알리다', memo: 'com(함께) + munic(나누다) + ate → 생각이나 정보를 서로 주고받으며 나누다 💡 뜻을 서로 통하게 하다.' },
  { id: 8031, day: 8, no: 31, word: 'companion', meaning: 'n. 친구, 동료', memo: 'com(함께) + pan(빵을 먹는 사람) → 밥(빵)을 함께 나누어 먹는 막골 동반자 💡 평생의 동반자.' },
  { id: 8032, day: 8, no: 32, word: 'accompany', meaning: 'v. ~와 동반하다, 동행하다', memo: 'ac(함께) + company(동료/무리) → 누군가의 곁에 함께 따라붙어 같이 이동하다 💡 부모와 동행하다.' },
  { id: 8033, day: 8, no: 33, word: 'comprise', meaning: 'v. 구성하다, 포함하다', memo: 'com(완전히) + prise(잡다) → 전체를 빈틈없이 품어서 이루다 💡 위원회는 5명으로 구성된다.' },
  { id: 8034, day: 8, no: 34, word: 'compound', meaning: 'n. 혼합물, 합성물 v. 혼합하다, 합성하다 a. 혼합[합성]의, 복합적인', memo: 'com(함께) + pound(치다/섞다) → 여러 가지 재료를 한데 넣고 뒤섞어 만들다 💡 화학 합성물.' },
  { id: 8035, day: 8, no: 35, word: 'confuse', meaning: 'v. 혼동하다; 혼란스럽게 하다', memo: 'con(함께) + fuse(녹여 붓다) → 경계선 없이 뒤죽박죽 섞어버려 어지럽히다 💡 두 단어를 혼동하다.' },
  { id: 8036, day: 8, no: 36, word: 'confirm', meaning: 'v. 확인해 주다, 입증하다; 승인하다', memo: 'con(완전히) + firm(확고한) → 사실 여부를 단단히 확인하고 확실히 매듭짓다 💡 예약 사항을 확인하다.' },
  { id: 8037, day: 8, no: 37, word: 'concentrate', meaning: 'v. 집중하다, 전념하다; 농축시키다 n. 농축물', memo: 'con(함께) + centr(중심) + ate → 시선이나 힘을 한곳의 중심으로 바짝 모으다 💡 공부에 집중하다.' },
  { id: 8038, day: 8, no: 38, word: 'constant', meaning: 'a. 끊임없는, 불변의 n. 변하지 않는 것, (수학) 상수', memo: 'con(계속) + stant(서 있는) → 제자리에 변함없이 꼿꼿이 계속 서 있는 💡 끊임없는 노력.' },
  { id: 8039, day: 8, no: 39, word: 'conflict', meaning: 'n. 갈등, 충돌', memo: 'con(서로 맞서) + flict(치다) → 서로 견해나 이해관계가 부딪쳐 싸우다 💡 의견 충돌.' },
  { id: 8040, day: 8, no: 40, word: 'consensus', meaning: 'n. 의견 일치, 합의', memo: 'con(함께) + sens(느끼다) → 다 같이 마음으로 느끼는 바가 똑같아 의견이 모아짐 💡 전원 합의.' },
  { id: 8041, day: 8, no: 41, word: 'correspond', meaning: 'v. 일치하다, 상응하다 (with/to); 서신을 주고받다, 통신하다 (with)', memo: 'cor(함께) + respond(답하다) → 상대방의 반응에 딱 들어맞거나 편지를 주고받다 💡 내용이 일치하다.' },
  { id: 8042, day: 8, no: 42, word: 'correlate', meaning: 'v. 상호 관련시키다, 연관성이 있다', memo: 'cor(함께) + relate(관련시키다) → 두 현상을 서로 연관 지어 관련성을 파악하다 💡 두 변수가 연관되다.' },
  { id: 8043, day: 8, no: 43, word: 'collaborate', meaning: 'v. 협력하다, 공동으로 일하다', memo: 'col(함께) + labor(일하다) → 뜻을 모아 한마디로 같이 열심히 힘을 합쳐 일하다 💡 프로젝트 공동 협력.' },
  { id: 8044, day: 8, no: 44, word: 'collide', meaning: 'v. 부딪치다, 충돌하다; (의견이) 일치하지 않다, 상충되다', memo: 'col(서로) + lide(치다) → 두 물체가 세게 마주 부딪치다 💡 자동차 정면충돌.' },
  { id: 8045, day: 8, no: 45, word: 'cooperate', meaning: 'v. 협력하다, 협조하다', memo: 'co(함께) + operate(작동하다/일하다) → 서로 손발을 맞춰 함께 일하다 💡 치안 유지를 위해 협조하다.' },
  { id: 8046, day: 8, no: 46, word: 'coherent', meaning: 'a. 일관성 있는, 논리 정연한', memo: 'co(함께) + her(착 달라붙다) + ent → 앞뒤 말이 빈틈없이 잘 짜여서 딱 들어맞는 💡 논리 정연한 주장.' },
  { id: 8047, day: 8, no: 47, word: 'symphony', meaning: 'n. 교향곡, 교향악단; 조화', memo: 'sym(함께) + phony(소리) → 여러 악기의 소리가 아름답게 하나로 어우러지다 💡 오케스트라 교향곡.' },
  { id: 8048, day: 8, no: 48, word: 'symbiosis', meaning: 'n. 공생(共生)', memo: 'sym(함께) + bio(생명) + sis → 서로 다른 생명체가 도움을 주며 함께 살아감 💡 자연의 공생 관계.' },
  { id: 8049, day: 8, no: 49, word: 'synchronize', meaning: 'v. 동시에 발생하다[움직인다], 동시에 발생하게[움직이게] 하다', memo: 'syn(함께) + chron(시간) → 시간(타이밍)을 정확히 일치시켜 같이 움직이다 💡 시계를 동기화하다.' },
  { id: 8050, day: 8, no: 50, word: 'synthetic', meaning: 'a. 합성한, 인조의; 종합적인 n. 합성물, 모조품', memo: 'syn(함께) + thetic(놓다/만들다) → 여러 성분을 인위적으로 조합해 만들어낸 💡 합성 섬유.' },
  { id: 9001, day: 9, no: 1, word: 'express', meaning: 'v. 표현하다, 나타내다 a. 급행의 n. 급행, 속달', memo: 'ex(밖으로) + press(누르다) → 마음속 생각을 밖으로 꾹 눌러 짜내어 나타내다 💡 감정을 표현하다.' },
  { id: 9002, day: 9, no: 2, word: 'extinct', meaning: 'a. 멸종된, 사라진', memo: 'ex(밖으로) + tinct(끌다/끄다) → 생명의 불꽃이 완전히 꺼져서 밖으로 사라지다 💡 공룡은 멸종되었다.' },
  { id: 9003, day: 9, no: 3, word: 'exhaust', meaning: 'v. 기진맥진하게 하다; 다 써 버리다', memo: 'ex(밖으로) + haust(끌어내다/물) → 에너지를 밖으로 다 뽑아내어 바닥나게 하다 💡 체력을 다 써 버리다.' },
  { id: 9004, day: 9, no: 4, word: 'exceptional', meaning: 'a. 예외적인, 아주 뛰어난', memo: 'ex(밖으로) + cept(잡다) → 일반적인 테두리 밖으로 튀어나와 특별하다 💡 예외적인 실력.' },
  { id: 9005, day: 9, no: 5, word: 'explode', meaning: 'v. 폭발하다, 터지다; 폭발적으로 증가하다', memo: 'ex(밖으로) + plode(박수치다/터지다) → 압력이 밖으로 터져 나오며 폭발하다 💡 폭탄이 폭발하다.' },
  { id: 9006, day: 9, no: 6, word: 'excel', meaning: 'v. 능가하다, (-보다) 뛰어나다', memo: 'ex(밖으로) + cel(위로 솟다) → 무리 중에서 위쪽으로 훌쩍 뛰어나오다 💡 실력이 남을 능가하다.' },
  { id: 9007, day: 9, no: 7, word: 'exotic', meaning: 'a. 이국적인, 외국의', memo: 'exo(밖의) + tic → 우리나라 영역 밖의 먼 나라에서 온 💡 이국적인 풍경.' },
  { id: 9008, day: 9, no: 8, word: 'exile', meaning: 'v. 추방하다 n. 추방(자), 망명(자)', memo: 'ex(밖으로) + ile(가게 하다) → 나라 밖으로 내쫓아버리다 💡 정치적 추방.' },
  { id: 9009, day: 9, no: 9, word: 'eradicate', meaning: 'v. 근절하다, 뿌리 뽑다', memo: 'e(밖으로) + radic(뿌리) → 식물의 뿌리를 통째로 뽑아내어 없애다 💡 빈곤을 근절하다.' },
  { id: 9010, day: 9, no: 10, word: 'extraordinary', meaning: 'a. 놀라운, 기이한; 비범한, 대단한', memo: 'extra(넘어서는) + ordinary(평범한) → 평범함을 훌쩍 뛰어넘어 놀랍다 💡 비범한 재능.' },
  { id: 9011, day: 9, no: 11, word: 'extravagant', meaning: 'a. 낭비하는, 사치스러운', memo: 'extra(밖으로) + vag(방황하다) + ant → 돈이나 재물이 한도를 넘어 밖으로 마구 새어나가다 💡 사치스러운 생활.' },
  { id: 9012, day: 9, no: 12, word: 'extrinsic', meaning: 'a. 외적인, 외부의, 비본질적인', memo: 'extr(밖의) + insic → 사물의 내면이 아니라 바깥쪽에 속하는 💡 외적인 요인.' },
  { id: 9013, day: 9, no: 13, word: 'outcome', meaning: 'n. 결과, 성과', memo: 'out(밖으로) + come(나오다) → 일의 진행 끝에 밖으로 도출되어 나온 결과 💡 좋은 성과.' },
  { id: 9014, day: 9, no: 14, word: 'outline', meaning: 'v. 윤곽을 그리다; 개요를 서술하다 n. 윤곽, 개요', memo: 'out(밖의) + line(선) → 바깥쪽 선을 따라 전체적인 테두리를 잡다 💡 계획의 개요.' },
  { id: 9015, day: 9, no: 15, word: 'outstanding', meaning: 'a. 뛰어난, 두드러진', memo: 'out(밖으로) + standing(서 있는) → 무리 중에서 우뚝 밖으로 솟아 나와 두드러지다 💡 뛰어난 업적.' },
  { id: 9016, day: 9, no: 16, word: 'outbreak', meaning: 'n. 발생, 발발', memo: 'out(밖으로) + break(깨고 나오다) → 억누르던 것이 밖으로 터져 나오며 시작되다 💡 전염병 발발.' },
  { id: 9017, day: 9, no: 17, word: 'outrage', meaning: 'n. 격분, 분노; 난폭한 행위 v. 격분하게 만들다', memo: 'out(넘어서) + rage(분노) → 이성을 밖으로 넘어서게 할 만큼의 큰 분노 💡 끔찍한 범죄에 격분하다.' },
  { id: 9018, day: 9, no: 18, word: 'outlaw', meaning: 'v. 금지하다, 불법화하다 n. 법복자', memo: 'out(밖으로) + law(법) → 법의 보호 바깥으로 내몰거나 법으로 금지하다 💡 총기를 불법화하다.' },
  { id: 9019, day: 9, no: 19, word: 'outspoken', meaning: 'a. 거리낌 없는, 솔직한', memo: 'out(밖으로) + spoken(말해지는) → 마음에 있는 말을 거침없이 밖으로 털어놓다 💡 솔직한 비판.' },
  { id: 9020, day: 9, no: 20, word: 'outdated', meaning: 'a. 시대에 뒤처진, 구식의', memo: 'out(지나간) + dated(날짜가 매겨진) → 날짜가 한참 지나 유행이 지난 💡 구식 방식을 바꾸다.' },
  { id: 9021, day: 9, no: 21, word: 'outweigh', meaning: 'v. ~보다 더 크다, ~보다 더 중요하다', memo: 'out(보다 우위에) + weigh(무게가 나가다) → 무게나 중요도가 상대보다 더 무겁다 💡 이점이 단점보다 크다.' },
  { id: 9022, day: 9, no: 22, word: 'decline', meaning: 'v. 감소[하락]하다, 쇠퇴하다; 거절하다 n. 감소, 하락, 쇠퇴', memo: 'de(아래로) + cline(기울다) → 아래쪽으로 기울어져 내리막길을 걷다 💡 인구가 감소하다.' },
  { id: 9023, day: 9, no: 23, word: 'declare', meaning: 'v. 선언하다, 발표하다; (세관에 물품을) 신고하다', memo: 'de(강하게) + clar(분명하게 하다) → 명백하게 밝혀서 공식적으로 선포하다 💡 지지를 선언하다.' },
  { id: 9024, day: 9, no: 24, word: 'debate', meaning: 'n. 토론, 논쟁', memo: 'de(철저히) + bate(치다/토론하다) → 서로 찬반 입장을 세워 치열하게 논쟁하다 💡 대선 토론.' },
  { id: 9025, day: 9, no: 25, word: 'devote', meaning: 'v. 바치다, 헌신하다, 전념하다', memo: 'de(아래로/전적으로) + vote(서약하다) → 마음을 다해 신성하게 모든 것을 바치다 💡 연구에 헌신하다.' },
  { id: 9026, day: 9, no: 26, word: 'depict', meaning: 'v. 그리다, 묘사하다', memo: 'de(완전히) + pict(그림/색칠하다) → 대상을 생생하게 그림으로 그려내다 💡 사회상을 묘사하다.' },
  { id: 9027, day: 9, no: 27, word: 'defect', meaning: 'n. 결함, 결정, 부족', memo: 'de(아래로) + fect(만들다) → 제대로 만들어지지 못하고 아래로 빠진 흠 💡 제품의 결함.' },
  { id: 9028, day: 9, no: 28, word: 'debase', meaning: 'v. (가치·품위 등을) 저하시키다, 떨어뜨리다', memo: 'de(아래로) + base(바닥/낮은) → 가치를 바닥으로 끌어내려 품위를 떨어뜨리다 💡 화폐 가치를 떨어뜨리다.' },
  { id: 9029, day: 9, no: 29, word: 'decay', meaning: 'v. 썩다, 부패하다, 쇠퇴하다 n. 부패, 쇠퇴', memo: 'de(아래로) + cay(떨어지다) → 아래로 무너지며 썩어 문드러지다 💡 치아 부식.' },
  { id: 9030, day: 9, no: 30, word: 'depart', meaning: 'v. 떠나다, 출발하다', memo: 'de(떨어져) + part(나누다/가다) → 있던 곳에서 떨어져 나와 길을 떠나다 💡 기차가 출발하다.' },
  { id: 9031, day: 9, no: 31, word: 'deprive', meaning: 'v. 빼앗다, 박탈하다', memo: 'de(떨어져) + prive(사적인 것) → 소중한 사유물이나 권리를 떼어내어 빼앗다 💡 권리를 박탈하다.' },
  { id: 9032, day: 9, no: 32, word: 'deliberate', meaning: 'a. 의도적인, 계획적인; 신중한 v. 숙고하다, 신중히 생각하다', memo: 'de(완전히) + liber(저울질하다) → 무게를 깊이 재어보듯 신중하고 계획적인 💡 의도적인 거짓말.' },
  { id: 9033, day: 9, no: 33, word: 'deceased', meaning: 'a. 사망한 n. 고인', memo: 'de(완전히) + ceased(끝난/멈춘) → 생명의 활동이 완전히 멈춘 💡 고인의 유산.' },
  { id: 9034, day: 9, no: 34, word: 'detach', meaning: 'v. 분리하다, 떼다', memo: 'de(떨어져) + tach(붙이다) → 붙어 있는 것을 떼어내어 분리하다 💡 꼬리표를 떼다.' },
  { id: 9035, day: 9, no: 35, word: 'default', meaning: 'n. 태만, 채무 불이행; 기본값[디폴트] v. 이행하지 않다, 체납하다', memo: 'de(아래로/부족) + fault(잘못) → 마땅히 해야 할 의무를 다하지 못함 💡 대출금 채무 불이행.' },
  { id: 9036, day: 9, no: 36, word: 'degrade', meaning: 'v. (가치·품위·직위 등을) 떨어뜨리다, 저하하다; (화학적으로) 분해되다[시키다]', memo: 'de(아래로) + grade(등급) → 등급이나 품격을 아래로 낮추다 💡 환경을 훼손하다.' },
  { id: 9037, day: 9, no: 37, word: 'degenerate', meaning: 'v. 퇴보[타락]하다, 악화되다 a. 퇴보한, 타락한', memo: 'de(아래로) + gener(발생하다/종족) → 질이 나빠져서 아래로 타락하다 💡 도덕적 퇴보.' },
  { id: 9038, day: 9, no: 38, word: 'decompose', meaning: 'v. 부패되다[시키다]; (성분·요소로) 분해되다[시키다]', memo: 'de(반대) + compose(구성하다) → 결합된 것을 해체하여 썩히거나 쪼개다 💡 유기물이 분해되다.' },
  { id: 9039, day: 9, no: 39, word: 'dehydrate', meaning: 'v. 탈수시키다, 건조시키다', memo: 'de(제거) + hydr(물) → 몸이나 사물에서 수분을 쏙 빼내다 💡 몸을 탈수시키다.' },
  { id: 9040, day: 9, no: 40, word: 'underline', meaning: 'v. 강조하다; 밑줄을 긋다', memo: 'under(아래에) + line(선을 긋다) → 중요한 글자 아래에 줄을 쳐서 강조하다 💡 핵심을 강조하다.' },
  { id: 9041, day: 9, no: 41, word: 'underlying', meaning: 'a. 근본적인; 밑에 있는', memo: 'under(아래에) + lying(놓여 있는) → 표면 아래 기저에 깔려 있는 근본적 요인 💡 근본적인 원인.' },
  { id: 9042, day: 9, no: 42, word: 'undergo', meaning: 'v. (변화·시련 등을) 겪다, 경험하다', memo: 'under(아래를 통과해) + go(가다) → 힘든 시련의 과정을 몸소 겪어나가다 💡 수술을 겪다.' },
  { id: 9043, day: 9, no: 43, word: 'undertake', meaning: 'v. (힘든 일을) 맡다, 수행하다, 착수하다', memo: 'under(아래에) + take(취하다) → 책임을 짊어지고 일에 뛰어들다 💡 프로젝트를 맡다.' },
  { id: 9044, day: 9, no: 44, word: 'undermine', meaning: 'v. 손상시키다, 약화시키다', memo: 'under(밑을) + mine(지뢰를 파다/파괴하다) → 기초 밑을 파내어 전체를 흔들고 약화시키다 💡 신뢰를 손상시키다.' },
  { id: 9045, day: 9, no: 45, word: 'subject', meaning: 'n. 대상, 피실험자; 주제, 과목 a. -에 영향을 받기 쉬운, 종속된 (to) v. (수동태로) 겪다, 처해지다', memo: 'sub(아래에) + ject(던지다) → 지배력 아래 던져져 영향권에 놓이다 💡 실험 대상.' },
  { id: 9046, day: 9, no: 46, word: 'subconscious', meaning: 'a. 잠재의식의 n. 잠재의식', memo: 'sub(아래에) + conscious(의식하는) → 의식의 깊은 바닥에 깔려 있는 마음 💡 잠재의식의 작용.' },
  { id: 9047, day: 9, no: 47, word: 'subtle', meaning: 'a. 미묘한; 섬세한', memo: 'sub(아래에) + tle(가늘게 짜다) → 눈에 잘 띄지 않게 은은하고 미묘하게 퍼져 있는 💡 미묘한 차이.' },
  { id: 9048, day: 9, no: 48, word: 'suburb', meaning: 'n. 교외', memo: 'sub(아래/근처에) + urb(도시) → 도시 중심가 주변의 주거 지역 💡 교외에 살다.' },
  { id: 9049, day: 9, no: 49, word: 'postwar', meaning: 'a. 전후(戰後)의', memo: 'post(이후에) + war(전쟁) → 전쟁이 끝난 그다음 시기의 💡 전후 복구 사업.' },
  { id: 9050, day: 9, no: 50, word: 'postpone', meaning: 'v. 연기하다, 미루다', memo: 'post(뒤로) + pone(놓다) → 일정을 시간상 뒤쪽으로 미뤄서 배치하다 💡 회의를 연기하다.' },
  { id: 10001, day: 10, no: 1, word: 'overcome', meaning: 'v. 극복하다, 이겨내다', memo: 'over(넘어서) + come(오다) → 시련과 장애물을 뛰어넘어 오다 💡 역경을 극복하다.' },
  { id: 10002, day: 10, no: 2, word: 'overtake', meaning: 'v. 앞지르다, 추월하다', memo: 'over(넘어) + take(잡다) → 상대보다 더 빨리 달려 앞서나가다 💡 자동차를 추월하다.' },
  { id: 10003, day: 10, no: 3, word: 'overlook', meaning: 'v. 간과하다, 못 보고 넘어가다; 눈감아 주다; 내려다보다', memo: 'over(위에서) + look(보다) → 위에서 아래를 내려다보거나 세심하게 보지 못하고 지나치다 💡 실수를 간과하다.' },
  { id: 10004, day: 10, no: 4, word: 'oversee', meaning: 'v. 감시하다, 감독하다', memo: 'over(위에서) + see(보다) → 전체를 위에서 굽어보며 관리 감독하다 💡 공사를 감시하다.' },
  { id: 10005, day: 10, no: 5, word: 'overall', meaning: 'a. 종합적인, 전체의', memo: 'over(전체에 걸쳐) + all(모두) → 모든 부분을 통틀어 아우르는 💡 종합적인 결과.' },
  { id: 10006, day: 10, no: 6, word: 'overlap', meaning: 'v. 겹치다, 중복되다 n. 중복', memo: 'over(위에) + lap(포개다) → 물건이나 범위가 서로 포개어져 겹치다 💡 일정이 겹치다.' },
  { id: 10007, day: 10, no: 7, word: 'overwhelm', meaning: 'v. 압도하다, 짓누르다, 사로잡다', memo: 'over(넘치게) + whelm(덮치다) → 거대한 파도처럼 완전히 덮쳐 정신을 못 차리게 하다 💡 공포에 압도되다.' },
  { id: 10008, day: 10, no: 8, word: 'overwork', meaning: 'v. 과로하다 n. 과로', memo: 'over(지나치게) + work(일하다) → 한도를 넘어서 무리하게 일하다 💡 과로로 쓰러지다.' },
  { id: 10009, day: 10, no: 9, word: 'overweight', meaning: 'a. 과체중의[중량 초과의], 비만의', memo: 'over(초과하여) + weight(무게) → 기준 무게보다 더 많이 나가다 💡 과체중 주의.' },
  { id: 10010, day: 10, no: 10, word: 'superior', meaning: 'a. ~보다 우수한 (to); 상급의 n. 윗사람, 상급자', memo: 'super(위에) + ior(더) → 남들보다 더 높은 위치에 있거나 뛰어난 💡 우수한 성능.' },
  { id: 10011, day: 10, no: 11, word: 'superb', meaning: 'a. 최고의, 뛰어난', memo: 'super(최고의) + b → 한눈에 봐도 훌륭하고 멋들어진 💡 최고의 솜씨.' },
  { id: 10012, day: 10, no: 12, word: 'supreme', meaning: 'a. 최고의, 대단한', memo: 'supre(가장 높은) + me → 권력이나 가치가 더 이상 위가 없을 정도로 최고인 💡 최고의 권력.' },
  { id: 10013, day: 10, no: 13, word: 'superstition', meaning: 'n. 미신', memo: 'super(넘는) + stit(서 있다) + ion → 이성적인 과학의 범위를 뛰어넘어 맹신하는 것 💡 오랜 미신.' },
  { id: 10014, day: 10, no: 14, word: 'supernatural', meaning: 'a. 초자연적인, 불가사의한 n. 초자연 현상', memo: 'super(초월한) + natural(자연의) → 자연 법칙의 한계를 뛰어넘은 신비로운 현상 💡 초자연적 현상.' },
  { id: 10015, day: 10, no: 15, word: 'superficial', meaning: 'a. 표면적인, 외적인, 피상적인', memo: 'super(위에) + ficial(얼굴/표면) → 깊이 들어가지 않고 겉면에만 머무르는 💡 피상적인 지식.' },
  { id: 10016, day: 10, no: 16, word: 'superfluous', meaning: 'a. 여분의, 남아도는', memo: 'super(넘쳐서) + fluous(흐르다) → 물이 넘쳐흐를 정도로 쓸데없이 많고 여유 있는 💡 불필요한 잔여물.' },
  { id: 10017, day: 10, no: 17, word: 'surplus', meaning: 'a. 과잉의, 남는 n. 과잉, 잉여, 흑자', memo: 'sur(초과) + plus(더하기) → 쓰고 남아서 더해진 잉여 분량 💡 무역 흑자.' },
  { id: 10018, day: 10, no: 18, word: 'surveillance', meaning: 'n. 감시, 감독', memo: 'sur(위에서) + veill(보다) + ance → 높은 곳에서 은밀하게 내려다보며 감시하다 💡 삼엄한 감시.' },
  { id: 10019, day: 10, no: 19, word: 'perform', meaning: 'v. 수행하다; 공연[연주/연기]하다', memo: 'per(완전히) + form(형태를 만들다) → 계획한 바를 끝까지 실천하여 모양새를 드러내다 💡 임무를 수행하다.' },
  { id: 10020, day: 10, no: 20, word: 'permit', meaning: 'v. 허락하다 n. 허가증', memo: 'per(통과하여) + mit(보내다) → 안으로 들어오거나 진행하도록 통과를 허용하다 💡 주차 허가증.' },
  { id: 10021, day: 10, no: 21, word: 'persist', meaning: 'v. 고집하다, 주장하다; 지속되다', memo: 'per(끝까지) + sist(서다) → 꺾이지 않고 끝까지 한자리를 고수하며 버티다 💡 주장을 고집하다.' },
  { id: 10022, day: 10, no: 22, word: 'persuade', meaning: 'v. 설득하다, 설득하여 ~하게 하다', memo: 'per(철저히) + suade(달래다/권하다) → 말로 잘 타일러 상대의 마음을 움직이다 💡 친구를 설득하다.' },
  { id: 10023, day: 10, no: 23, word: 'permanent', meaning: 'a. 영구적인, 불변의', memo: 'per(완전히) + manent(머물다) → 변함없이 그 자리에 영원히 머물러 있는 💡 영구적인 해결책.' },
  { id: 10024, day: 10, no: 24, word: 'perpetual', meaning: 'a. 영구적인, 끊임없는', memo: 'per(계속) + pet(추구하다/가다) + ual → 끝없이 지속되어 멈추지 않는 💡 끊임없는 논쟁.' },
  { id: 10025, day: 10, no: 25, word: 'persevere', meaning: 'v. 인내하다, 견디다, 꾸준히 노력하다', memo: 'per(끝까지) + severe(엄격한/매달리는) → 힘든 시련 속에서도 끝까지 엄격하게 버텨내다 💡 끝까지 인내하다.' },
  { id: 10026, day: 10, no: 26, word: 'perish', meaning: 'v. 죽다, 소멸하다; (음식이) 상하다', memo: 'per(완전히) + ish(사라지다) → 완전히 망가져서 소멸하거나 썩어 없어지다 💡 농작물이 말라 죽다.' },
  { id: 10027, day: 10, no: 27, word: 'transfer', meaning: 'v. 옮기다, 이동하다; 전학[전근] 가다 n. 이동; 전학, 전근', memo: 'trans(이동) + fer(나르다) → 이리저리 장소나 자리를 옮겨 나르다 💡 부서 이동.' },
  { id: 10028, day: 10, no: 28, word: 'translate', meaning: 'v. 번역하다, 통역하다; (다른 형태론) 옮기다, 바꾸다', memo: 'trans(넘어) + late(말을 전하다) → 한쪽 언어에서 다른 쪽 언어로 말을 옮겨 표현하다 💡 문장을 번역하다.' },
  { id: 10029, day: 10, no: 29, word: 'transact', meaning: 'v. 거래하다', memo: 'trans(건너서) + act(행동하다) → 서로 주고받으며 비즈니스 업무를 처리하다 💡 은행 거래를 하다.' },
  { id: 10030, day: 10, no: 30, word: 'transit', meaning: 'n. 통과, 통행; 운송, 운반', memo: 'trans(건너서) + it(가다) → 이쪽에서 저쪽으로 지나쳐 이동함 💡 대중교통 이용.' },
  { id: 10031, day: 10, no: 31, word: 'transition', meaning: 'n. 전환, 변천, 과도기', memo: 'trans(이동) + ition(과정) → 상태나 시기가 다른 단계로 스르륵 넘어가 바뀜 💡 사회적 대전환.' },
  { id: 10032, day: 10, no: 32, word: 'transparent', meaning: 'a. 투명한, 비치는', memo: 'trans(통하여) + parent(나타나는) → 빛이나 형체가 반대편으로 훤히 투명하게 비치다 💡 투명한 유리.' },
  { id: 10033, day: 10, no: 33, word: 'interval', meaning: 'n. 간격, 사이; 중간 휴식 시간', memo: 'inter(사이에) + val(벽/공간) → 시간이나 공간 사이의 빈격 💡 짧은 휴식 시간.' },
  { id: 10034, day: 10, no: 34, word: 'intermediate', meaning: 'a. 중간의, 중급의 n. 중급자, 중개자', memo: 'inter(사이에) + medi(중앙의) + ate → 단계와 단계 사이의 중간 지점에 위치한 💡 중급 영어 회화.' },
  { id: 10035, day: 10, no: 35, word: 'interact', meaning: 'v. 상호 작용하다 (with)', memo: 'inter(서로 사이에) + act(행동하다) → 서로 영향을 주고받으며 반응하다 💡 환경과 상호 작용하다.' },
  { id: 10036, day: 10, no: 36, word: 'interpret', meaning: 'v. 해석하다, 이해하다; 통역하다', memo: 'inter(사이를) + pret(가격매기다/설명하다) → 숨은 의미의 맥락을 짚어내어 뜻을 풀이하다 💡 꿈을 해석하다.' },
  { id: 10037, day: 10, no: 37, word: 'intervene', meaning: 'v. 개입하다, 중재하다, 끼어들다', memo: 'inter(사이에) + vene(오다) → 두 사람 사이에 쑥 끼어들어 간섭하거나 중재하다 💡 싸움에 개입하다.' },
  { id: 10038, day: 10, no: 38, word: 'interdependent', meaning: 'a. 상호 의존적인', memo: 'inter(서로) + dependent(의존하는) → 혼자 살 수 없고 서로가 서로에게 의지하는 💡 상호 의존적 관계.' },
  { id: 10039, day: 10, no: 39, word: 'intertwine', meaning: 'v. 뒤얽다, 엮다; (주로 수동태로) 밀접하게 관련되다', memo: 'inter(서로) + twine(실을 꼬다) → 실처럼 양쪽이 단단하게 꼬여서 얽히다 💡 운명이 밀접하게 얽히다.' },
  { id: 10040, day: 10, no: 40, word: 'intersection', meaning: 'n. 교차로', memo: 'inter(사이에) + sect(자르다) + ion → 길이 서로 가로지르며 교차하는 지점 💡 사거리 교차로.' },
  { id: 10041, day: 10, no: 41, word: 'contrary', meaning: 'a. 반대의, 상반되는 n. 정반대', memo: 'contra(반대로) + ry → 방향이나 성질이 완전히 정반대로 향하는 💡 정반대의 의견.' },
  { id: 10042, day: 10, no: 42, word: 'contrast', meaning: 'n. 대조, 대비 v. 대조를 이루다', memo: 'contra(반대로) + st(서다) → 서로 반대되는 것끼리 나란히 세워 차이를 극명하게 보여주다 💡 명확한 대비.' },
  { id: 10043, day: 10, no: 43, word: 'encounter', meaning: 'v. 맞닥뜨리다, 우연히 만나다 n. 만남, 충돌', memo: 'en(안에) + counter(마주하여) → 예상치 못하게 정면으로 마주치다 💡 예상치 못한 만남.' },
  { id: 10044, day: 10, no: 44, word: 'counterpart', meaning: 'n. 상대, 상응하는 것[사람]', memo: 'counter(상응하는) + part(역할/부분) → 상대방 진영에서 똑같은 역할을 맡고 있는 대응물 💡 협상 상대방.' },
  { id: 10045, day: 10, no: 45, word: 'counteract', meaning: 'v. 대응하다, 거스르다; 상쇄하다', memo: 'counter(반대로) + act(행동하다) → 나쁜 작용에 맞서 반대 방향으로 힘을 가해 막다 💡 독성을 상쇄하다.' },
  { id: 10046, day: 10, no: 46, word: 'counterfeit', meaning: 'v. 위조하다 a. 위조의, 가짜의', memo: 'counter(가짜의) + feit(만들다) → 정품과 똑같이 흉내 내어 가짜로 만들어내다 💡 위조 지폐.' },
  { id: 10047, day: 10, no: 47, word: 'antisocial', meaning: 'a. 반사회적인, 비사회적인', memo: 'anti(반대하여) + social(사회의) → 사회 질서에 어긋나거나 해를 끼치는 💡 반사회적 행동.' },
  { id: 10048, day: 10, no: 48, word: 'antibody', meaning: 'n. 항체', memo: 'anti(대항하는) + body(몸/물질) → 체내에 침입한 병원균에 대항하여 맞서는 면역 물질 💡 항체 생성.' },
  { id: 10049, day: 10, no: 49, word: 'antibiotic', meaning: 'a. 항생의 n. 항생 물질, 항생제', memo: 'anti(대항하는) + biotic(생물의) → 박테리아(세균) 생명체에 대항하여 죽이는 약물 💡 항생제 처방.' },
  { id: 10050, day: 10, no: 50, word: 'antagonist', meaning: 'n. 적대자', memo: 'ant(반대로) + agonist(경기자/싸우는 자) → 주인공에 맞서서 싸우는 라이벌이나 적대 인물 💡 이야기 속 적대자.' },
];
